Repository krahets/hello-algo, pull requests merged in 2022-12, with the labels that each got.

#70 Update stack.md
  codes/javascript/chapter_stack_and_queue/stack.js
  codes/typescript/chapter_stack_and_queue/stack.ts
  docs/chapter_stack_and_queue/stack.md
Labels: code translation

#73 Add TypeScript code and docs for Chapter of Array
  codes/typescript/chapter_array_and_linkedlist/array.ts
  docs/chapter_array_and_linkedlist/array.md
Labels: coding

#71 add JavaScript codes for Tree
  codes/javascript/chapter_tree/binary_search_tree.js
  codes/javascript/chapter_tree/binary_tree.js
  codes/javascript/chapter_tree/binary_tree_bfs.js
  codes/javascript/chapter_tree/binary_tree_dfs.js
  codes/javascript/include/PrintUtil.js
  codes/javascript/include/TreeNode.js
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree.md
Labels: coding

#81 Array stack in js and ts
  codes/javascript/chapter_stack_and_queue/array_stack.js
  codes/typescript/chapter_stack_and_queue/array_stack.ts
  docs/chapter_stack_and_queue/stack.md
Labels: coding

#68 Create 'avl_tree' and modify 'TreeNode.hpp' to support 'avl_tree'
  codes/cpp/chapter_tree/avl_tree.cpp
  codes/cpp/include/TreeNode.hpp
  codes/java/include/TreeNode.java
  docs/chapter_tree/avl_tree.assets/degradation_from_inserting_node.png
  docs/chapter_tree/avl_tree.assets/degradation_from_removing_node.png
  docs/chapter_tree/avl_tree.assets/left_right_rotate.png
  docs/chapter_tree/avl_tree.assets/left_rotate_with_grandchild.png
  docs/chapter_tree/avl_tree.assets/right_left_rotate.png
  docs/chapter_tree/avl_tree.assets/right_rotate_step1.png
  docs/chapter_tree/avl_tree.assets/right_rotate_step2.png
  docs/chapter_tree/avl_tree.assets/right_rotate_step3.png
  docs/chapter_tree/avl_tree.assets/right_rotate_step4.png
  docs/chapter_tree/avl_tree.assets/right_rotate_with_grandchild.png
  docs/chapter_tree/avl_tree.assets/rotation_cases.png
  docs/chapter_tree/avl_tree.md
  mkdocs.yml
Labels: writing

#92 Insertion sort using go
  codes/go/chapter_sorting/insertion_sort/insertion_sort.go
  codes/go/chapter_sorting/insertion_sort/insertion_sort_test.go
  docs/chapter_sorting/insertion_sort.md
Labels: coding

#104 Fix the PrintUtil.js showTrunks and Update JavaScript and docs' style (Chapter of Tree)
  codes/javascript/chapter_tree/binary_search_tree.js
  codes/javascript/chapter_tree/binary_tree.js
  codes/javascript/chapter_tree/binary_tree_bfs.js
  codes/javascript/chapter_tree/binary_tree_dfs.js
  codes/javascript/include/PrintUtil.js
  codes/javascript/include/TreeNode.js
  docs/chapter_tree/binary_tree.md
Labels: correction, coding

#106 Add C# code to array doc
  codes/c#/chapter_array_and_linkedlist/Array.cs
  docs/chapter_array_and_linkedlist/array.md
Labels: coding

#123 Update hash_map.md
  docs/chapter_hashing/hash_map.md
Labels: correction

#124 Update intro_to_sort.md
  docs/chapter_sorting/intro_to_sort.md
Labels: correction

#110 Add C++, Python, Go code for chapter_hashing
  codes/cpp/chapter_hashing/array_hash_map.cpp
  codes/cpp/chapter_hashing/hash_map.cpp
  codes/cpp/include/PrintUtil.hpp
  codes/go/chapter_hashing/array_hash_map.go
  codes/go/chapter_hashing/array_hash_map_test.go
  codes/go/chapter_hashing/hash_map_test.go
  codes/go/pkg/print_utils.go
  codes/java/chapter_hashing/array_hash_map.java
  codes/python/chapter_hashing/array_hash_map.py
  codes/python/chapter_hashing/hash_map.py
  codes/python/include/__init__.py
  codes/python/include/print_util.py
  docs/chapter_hashing/hash_map.md
Labels: coding

#116 Add JS for chapter of computational complexity
  codes/javascript/chapter_computational_complexity/leetcode_two_sum.js
  docs/chapter_computational_complexity/space_time_tradeoff.md
Labels: coding

#126 function PrintSlice supports Generics
  codes/go/chapter_searching/linear_search.go
  codes/go/pkg/print_utils.go
  docs/chapter_searching/linear_search.md
Labels: correction, coding

#125 Add C# linkedlist doc and code,modify some formatting.
  codes/csharp/.gitignore
  codes/csharp/chapter_array_and_linkedlist/Array.cs
  codes/csharp/chapter_array_and_linkedlist/LinkedList.cs
  codes/csharp/hello-algo.csproj
  codes/csharp/include/ListNode.cs
  docs/chapter_array_and_linkedlist/linked_list.md
Labels: coding

#161 Update installation.md
  docs/chapter_preface/installation.md
Labels: polishing

#191 Add insertion sort in C
  codes/c/chapter_sorting/insertion_sort.c
  docs/chapter_sorting/insertion_sort.md
Labels: coding
