Repository krahets/hello-algo, pull requests merged in 2023-07, with the labels that each got.

#588 feat: add the section of dp solution pipeline
  codes/python/chapter_dynamic_programming/min_path_sum.py
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dfs.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dfs_mem.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step1.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step10.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step11.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step12.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step2.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step3.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step4.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step5.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step6.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step7.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step8.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_dp_step9.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_example.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_step1.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_step2.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_step3.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.md
  mkdocs.yml
Labels: coding, writing

#599 feat: Add the section of edit distance problem
  codes/cpp/chapter_dynamic_programming/CMakeLists.txt
  codes/cpp/chapter_dynamic_programming/edit_distance.cpp
  codes/java/chapter_dynamic_programming/edit_distance.java
  codes/python/chapter_dynamic_programming/edit_distance.py
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_decision_tree.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step1.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step10.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step11.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step12.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step13.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step14.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step15.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step2.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step3.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step4.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step5.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step6.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step7.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step8.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_dp_step9.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_example.png
  docs/chapter_dynamic_programming/edit_distance_problem.assets/edit_distance_state_transfer.png
  docs/chapter_dynamic_programming/edit_distance_problem.md
  mkdocs.yml
Labels: coding, writing

#606 rust and zig : add codes for chapter_dynamic_programming
  codes/rust/Cargo.toml
  codes/rust/chapter_backtracking/n_queens.rs
  codes/rust/chapter_backtracking/permutations_i.rs
  codes/rust/chapter_backtracking/permutations_ii.rs
  codes/rust/chapter_dynamic_programming/climbing_stairs_dfs.rs
  codes/rust/chapter_dynamic_programming/climbing_stairs_dfs_mem.rs
  codes/rust/chapter_dynamic_programming/climbing_stairs_dp.rs
  codes/rust/chapter_dynamic_programming/coin_change.rs
  codes/rust/chapter_dynamic_programming/coin_change_ii.rs
  codes/rust/chapter_dynamic_programming/edit_distance.rs
  codes/rust/chapter_dynamic_programming/knapsack.rs
  codes/rust/chapter_dynamic_programming/min_cost_climbing_stairs_dp.rs
  codes/rust/chapter_dynamic_programming/min_path_sum.rs
  codes/rust/chapter_dynamic_programming/unbounded_knapsack.rs
  codes/zig/build.zig
  codes/zig/chapter_dynamic_programming/climbing_stairs_backtrack.zig
  codes/zig/chapter_dynamic_programming/climbing_stairs_constraint_dp.zig
  codes/zig/chapter_dynamic_programming/climbing_stairs_dfs.zig
  codes/zig/chapter_dynamic_programming/climbing_stairs_dfs_mem.zig
  codes/zig/chapter_dynamic_programming/climbing_stairs_dp.zig
  codes/zig/chapter_dynamic_programming/coin_change.zig
  codes/zig/chapter_dynamic_programming/coin_change_ii.zig
  codes/zig/chapter_dynamic_programming/edit_distance.zig
  codes/zig/chapter_dynamic_programming/knapsack.zig
  codes/zig/chapter_dynamic_programming/min_cost_climbing_stairs_dp.zig
  codes/zig/chapter_dynamic_programming/min_path_sum.zig
  codes/zig/chapter_dynamic_programming/unbounded_knapsack.zig
Labels: coding

#605 feat: add rust codes for avl tree
  codes/rust/Cargo.toml
  codes/rust/chapter_tree/avl_tree.rs
  codes/rust/include/tree_node.rs
Labels: coding

#609 feat: Add the chapter of divide and conquer
  codes/python/chapter_divide_and_conquer/build_tree.py
  docs/chapter_divide_and_conquer/build_binary_tree.assets/build_tree_division_pointers.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/build_tree_example.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/build_tree_preorder_inorder_division.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step1.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step10.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step2.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step3.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step4.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step5.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step6.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step7.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step8.png
  docs/chapter_divide_and_conquer/build_binary_tree.assets/built_tree_step9.png
  docs/chapter_divide_and_conquer/build_binary_tree.md
  docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_bubble_sort.png
  docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_merge_sort.png
  docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_parallel_computing.png
  docs/chapter_divide_and_conquer/divide_and_conquer.md
  docs/chapter_divide_and_conquer/index.md
  mkdocs.yml
Labels: coding, writing

#612 feat: add rust codes for chapter heap
  codes/rust/Cargo.toml
  codes/rust/chapter_heap/heap.rs
  codes/rust/chapter_heap/my_heap.rs
  codes/rust/chapter_heap/top_k.rs
  codes/rust/include/print_util.rs
Labels: coding

#614 feat: Add the section of hanota problem.
  codes/python/chapter_divide_and_conquer/hanota.py
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_divide_and_conquer.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_example.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f1_step1.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f1_step2.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step1.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step2.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step3.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step4.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step1.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step2.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step3.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step4.png
  docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_recursive_tree.png
  docs/chapter_divide_and_conquer/hanota_problem.md
  mkdocs.yml
Labels: coding, writing

#608 Feature/chapter dynamic programming swift
  codes/swift/Package.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_backtrack.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_constraint_dp.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_dfs.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_dfs_mem.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_dp.swift
  codes/swift/chapter_dynamic_programming/coin_change.swift
  codes/swift/chapter_dynamic_programming/coin_change_ii.swift
  codes/swift/chapter_dynamic_programming/edit_distance.swift
  codes/swift/chapter_dynamic_programming/knapsack.swift
  codes/swift/chapter_dynamic_programming/min_cost_climbing_stairs_dp.swift
  codes/swift/chapter_dynamic_programming/min_path_sum.swift
  codes/swift/chapter_dynamic_programming/unbounded_knapsack.swift
Labels: coding

#633 feat: Add the chapter of greedy
  codes/cpp/CMakeLists.txt
  codes/cpp/chapter_greedy/CMakeLists.txt
  codes/cpp/chapter_greedy/coin_change_greedy.cpp
  codes/cpp/chapter_greedy/fractional_knapsack.cpp
  codes/cpp/chapter_hashing/CMakeLists.txt
  codes/java/chapter_greedy/coin_change_greedy.java
  codes/java/chapter_greedy/fractional_knapsack.java
  codes/python/chapter_greedy/coin_change_greedy.py
  codes/python/chapter_greedy/fractional_knapsack.py
  docs/assets/covers/chapter_greedy.jpg
  docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_area_chart.png
  docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_example.png
  docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_greedy_strategy.png
  docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_unit_value.png
  docs/chapter_greedy/fractional_knapsack_problem.md
  docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_strategy.png
  docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_vs_dp.png
  docs/chapter_greedy/greedy_algorithm.md
  docs/chapter_greedy/index.md
  mkdocs.yml
Labels: coding, writing

#639 feat: Add the section of max capacity problem
  codes/cpp/chapter_greedy/CMakeLists.txt
  codes/cpp/chapter_greedy/max_capacity.cpp
  codes/java/chapter_greedy/max_capacity.java
  codes/python/chapter_greedy/max_capacity.py
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_example.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step1.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step2.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step3.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step4.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step5.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step6.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step7.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step8.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step9.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_initial_state.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_long_board.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_short_board.png
  docs/chapter_greedy/max_capacity_problem.assets/max_capacity_skipped_states.png
  docs/chapter_greedy/max_capacity_problem.md
  mkdocs.yml
Labels: coding, writing

#642 feat: Add the section of max product cutting problem.
  codes/cpp/chapter_greedy/max_product_cutting.cpp
  codes/java/chapter_greedy/max_product_cutting.java
  codes/python/chapter_greedy/max_product_cutting.py
  docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_definition.png
  docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_calculation.png
  docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer1.png
  docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer2.png
  docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer3.png
  docs/chapter_greedy/max_product_cutting_problem.md
  mkdocs.yml
Labels: coding

#641 Update hash_map.md
  docs/chapter_hashing/hash_map.md
Labels: bug, writing

#647 fix: add space in print
  codes/java/chapter_greedy/max_product_cutting.java
Labels: bug, coding

#655 feat(go/tree): support array binary tree
  codes/go/chapter_backtracking/preorder_traversal_i_compact.go
  codes/go/chapter_backtracking/preorder_traversal_ii_compact.go
  codes/go/chapter_backtracking/preorder_traversal_iii_compact.go
  codes/go/chapter_backtracking/preorder_traversal_test.go
  codes/go/chapter_tree/array_binary_tree.go
  codes/go/chapter_tree/array_binary_tree_test.go
  codes/go/chapter_tree/avl_tree.go
  codes/go/chapter_tree/binary_search_tree.go
  codes/go/chapter_tree/binary_tree_bfs.go
  codes/go/chapter_tree/binary_tree_bfs_test.go
  codes/go/chapter_tree/binary_tree_dfs.go
  codes/go/chapter_tree/binary_tree_dfs_test.go
  codes/go/pkg/print_utils.go
  codes/go/pkg/tree_node.go
  codes/go/pkg/tree_node_test.go
Labels: coding

#593 feat: Add C codes for the chapter backtracking
  codes/c/CMakeLists.txt
  codes/c/chapter_backtracking/CMakeLists.txt
  codes/c/chapter_backtracking/permutations_i.c
  codes/c/chapter_backtracking/preorder_traversal_i_compact.c
  codes/c/chapter_backtracking/preorder_traversal_ii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_template.c
  codes/c/chapter_backtracking/subset_sum_i.c
  codes/c/chapter_backtracking/subset_sum_i_naive.c
  codes/c/chapter_backtracking/subset_sum_ii.c
  codes/c/utils/common.h
  codes/c/utils/vector.h
Labels: coding

#663 Fix space_complexity.c build error.
  codes/c/chapter_computational_complexity/space_complexity.c
Labels: bug, coding

#669 Update summary.md in chapter_hashing
  docs/chapter_hashing/summary.md
Labels: bug, coding
