Repository krahets/hello-algo, pull requests merged in 2023-08, with the labels that each got.

#670 feat: Add opening phrase for every chapters
  docs/assets/covers/chapter_array_and_linkedlist.jpg
  docs/assets/covers/chapter_backtracking.jpg
  docs/assets/covers/chapter_dynamic_programming.jpg
  docs/assets/covers/chapter_greedy.jpg
  docs/assets/covers/chapter_heap.jpg
  docs/assets/covers/chapter_sorting.jpg
  docs/chapter_array_and_linkedlist/index.md
  docs/chapter_backtracking/index.md
  docs/chapter_computational_complexity/index.md
  docs/chapter_data_structure/index.md
  docs/chapter_divide_and_conquer/index.md
  docs/chapter_dynamic_programming/index.md
  docs/chapter_graph/index.md
  docs/chapter_greedy/index.md
  docs/chapter_hashing/index.md
  docs/chapter_heap/index.md
  docs/chapter_introduction/index.md
  docs/chapter_preface/index.md
  docs/chapter_searching/index.md
  docs/chapter_sorting/index.md
  docs/chapter_stack_and_queue/index.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/index.md
  docs/index.md
Labels: writing

#667 feat(chapter_backtracking): Add js and ts codes for chapter 13.3
  codes/javascript/chapter_array_and_linkedlist/array.js
  codes/javascript/chapter_backtracking/subset_sum_i.js
  codes/javascript/chapter_backtracking/subset_sum_i_naive.js
  codes/javascript/chapter_backtracking/subset_sum_ii.js
  codes/javascript/chapter_computational_complexity/time_complexity.js
  codes/javascript/chapter_divide_and_conquer/binary_search_recur.js
  codes/javascript/chapter_divide_and_conquer/build_tree.js
  codes/javascript/chapter_divide_and_conquer/hanota.js
  codes/javascript/chapter_dynamic_programming/climbing_stairs_dfs.js
  codes/javascript/chapter_dynamic_programming/climbing_stairs_dfs_mem.js
  codes/javascript/chapter_dynamic_programming/climbing_stairs_dp.js
  codes/javascript/chapter_graph/graph_adjacency_matrix.js
  codes/javascript/chapter_heap/my_heap.js
  codes/javascript/chapter_searching/binary_search_edge.js
  codes/javascript/chapter_stack_and_queue/array_queue.js
  codes/javascript/chapter_stack_and_queue/linkedlist_stack.js
  codes/typescript/chapter_backtracking/subset_sum_i.ts
  codes/typescript/chapter_backtracking/subset_sum_i_naive.ts
  codes/typescript/chapter_backtracking/subset_sum_ii.ts
  codes/typescript/chapter_computational_complexity/time_complexity.ts
  codes/typescript/chapter_divide_and_conquer/binary_search_recur.ts
  codes/typescript/chapter_divide_and_conquer/build_tree.ts
  codes/typescript/chapter_divide_and_conquer/hanota.ts
  codes/typescript/chapter_dynamic_programming/climbing_stairs_dfs.ts
  codes/typescript/chapter_dynamic_programming/climbing_stairs_dfs_mem.ts
  codes/typescript/chapter_dynamic_programming/climbing_stairs_dp.ts
  codes/typescript/chapter_graph/graph_adjacency_matrix.ts
  codes/typescript/chapter_heap/my_heap.ts
  codes/typescript/chapter_searching/binary_search_edge.ts
  codes/typescript/chapter_stack_and_queue/array_queue.ts
  codes/typescript/chapter_stack_and_queue/linkedlist_stack.ts
Labels: coding

#671 feat: Add the section of binary search insertion.
  codes/c/chapter_searching/binary_search_edge.c
  codes/cpp/chapter_searching/CMakeLists.txt
  codes/cpp/chapter_searching/binary_search_edge.cpp
  codes/cpp/chapter_searching/binary_search_insertion.cpp
  codes/csharp/chapter_searching/binary_search_edge.cs
  codes/dart/chapter_searching/binary_search_edge.dart
  codes/go/chapter_searching/binary_search_edge.go
  codes/go/chapter_searching/binary_search_test.go
  codes/java/chapter_searching/binary_search_edge.java
  codes/java/chapter_searching/binary_search_insertion.java
  codes/javascript/chapter_searching/binary_search_edge.js
  codes/python/chapter_searching/binary_search_edge.py
  codes/python/chapter_searching/binary_search_insertion.py
  codes/rust/chapter_searching/binary_search_edge.rs
  codes/swift/chapter_searching/binary_search_edge.swift
  codes/typescript/chapter_searching/binary_search_edge.ts
  docs/chapter_searching/binary_search.assets/binary_search_example.png
  docs/chapter_searching/binary_search.assets/binary_search_ranges.png
  docs/chapter_searching/binary_search.assets/binary_search_step0.png
  docs/chapter_searching/binary_search.assets/binary_search_step1.png
  docs/chapter_searching/binary_search.assets/binary_search_step2.png
  docs/chapter_searching/binary_search.assets/binary_search_step3.png
  docs/chapter_searching/binary_search.assets/binary_search_step4.png
  docs/chapter_searching/binary_search.assets/binary_search_step5.png
  docs/chapter_searching/binary_search.assets/binary_search_step6.png
  docs/chapter_searching/binary_search.assets/binary_search_step7.png
  docs/chapter_searching/binary_search.md
  docs/chapter_searching/binary_search_edge.assets/binary_search_edge_by_element.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_naive.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step1.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step2.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step3.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step4.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step5.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step6.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step7.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_edge_step8.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_left_right_edge.png
  docs/chapter_searching/binary_search_edge.assets/binary_search_right_edge_by_left_edge.png
  docs/chapter_searching/binary_search_edge.md
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_example.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_naive.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step1.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step2.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step3.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step4.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step5.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step6.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step7.png
  docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step8.png
  docs/chapter_searching/binary_search_insertion.md
  mkdocs.yml
Labels: coding, writing, polishing

#685 Fix the bug of index in rust codes
  codes/rust/chapter_searching/binary_search.rs
Labels: bug, coding

#687 fix(docs): add official configuration tutorial for csharp
  docs/chapter_appendix/installation.md
Labels: writing, polishing

#695 Fix a typo
  docs/chapter_data_structure/basic_data_types.md
Labels: bug, writing

#696 feat: Add Dart Codes for section_iteration_and_recursion
  codes/dart/chapter_computational_complexity/iteration.dart
  codes/dart/chapter_computational_complexity/recursion.dart
Labels: coding

#698 feat(go): add iterration/recursion & fix bugs
  codes/c/chapter_heap/my_heap.c
  codes/go/chapter_computational_complexity/iteration.go
  codes/go/chapter_computational_complexity/iteration_test.go
  codes/go/chapter_computational_complexity/recursion.go
  codes/go/chapter_computational_complexity/recursion_test.go
  codes/go/chapter_heap/my_heap.go
Labels: bug, coding

#700 Update backtracking_algorithm.md
  docs/chapter_backtracking/backtracking_algorithm.md
Labels: bug, writing

#699 fix: binary_search.md
  docs/chapter_searching/binary_search.md
Labels: bug, writing

#708 fix: fix a typo
  docs/chapter_array_and_linkedlist/linked_list.md
Labels: bug, writing

#692 feat: add dynamic programming code for JS and TS
  codes/java/chapter_dynamic_programming/min_path_sum.java
  codes/javascript/chapter_dynamic_programming/climbing_stairs_constraint_dp.js
  codes/javascript/chapter_dynamic_programming/coin_change.js
  codes/javascript/chapter_dynamic_programming/coin_change_ii.js
  codes/javascript/chapter_dynamic_programming/edit_distance.js
  codes/javascript/chapter_dynamic_programming/knapsack.js
  codes/javascript/chapter_dynamic_programming/min_cost_climbing_stairs_dp.js
  codes/javascript/chapter_dynamic_programming/min_path_sum.js
  codes/javascript/chapter_dynamic_programming/unbounded_knapsack.js
  codes/typescript/chapter_backtracking/n_queens.ts
  codes/typescript/chapter_dynamic_programming/climbing_stairs_constraint_dp.ts
  codes/typescript/chapter_dynamic_programming/coin_change.ts
  codes/typescript/chapter_dynamic_programming/coin_change_ii.ts
  codes/typescript/chapter_dynamic_programming/edit_distance.ts
  codes/typescript/chapter_dynamic_programming/knapsack.ts
  codes/typescript/chapter_dynamic_programming/min_cost_climbing_stairs_dp.ts
  codes/typescript/chapter_dynamic_programming/min_path_sum.ts
  codes/typescript/chapter_dynamic_programming/unbounded_knapsack.ts
Labels: coding
