Repository krahets/hello-algo, pull requests merged in 2023-02, with the labels that each got.

#322 插入排序: 修改插入排序思想描述
  docs/chapter_sorting/insertion_sort.md
Labels: polishing

#331 Add JavaScript and TypeScript code and docs for Section Space Complexity
  codes/javascript/chapter_computational_complexity/space_complexity.js
  codes/javascript/chapter_searching/hashing_search.js
  codes/typescript/chapter_computational_complexity/space_complexity.ts
  docs/chapter_computational_complexity/space_complexity.md
Labels: coding

#340 二叉搜索树: 排序小节 移动到 删除结点代码 的下面
  codes/java/chapter_stack_and_queue/linkedlist_deque.java
  docs/chapter_tree/binary_search_tree.md
Labels: correction

#341 fix: 颗 -> 棵
  docs/chapter_heap/heap.md
Labels: correction

#343 fix: 颗 -> 棵
  docs/chapter_heap/heap.md
Labels: correction

#349 Add TypeScript code and docs to Chapter of Heap
  codes/typescript/chapter_heap/my_heap.ts
  codes/typescript/module/PrintUtil.ts
  docs/chapter_heap/heap.md
Labels: coding

#350 病句修改，缺少谓语
  docs/chapter_computational_complexity/performance_evaluation.md
Labels: bug, polishing

#353 Update time_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: writing, polishing

#356 Update leetcode_two_sum.zig and leetcode_two_sum.rs
  codes/rust/chapter_computational_complexity/leetcode_two_sum.rs
  codes/zig/chapter_computational_complexity/leetcode_two_sum.zig
Labels: coding, polishing

#352 feat: add array C docs
  docs/chapter_array_and_linkedlist/array.md
Labels: coding

#360 fix the function poll() in my_heap.cpp
  codes/cpp/chapter_heap/my_heap.cpp
Labels: bug, coding

#361 Update heap.md
  docs/chapter_heap/heap.md
Labels: bug, writing

#365 Update installation.md
  docs/chapter_preface/installation.md
Labels: writing, polishing

#367 feat: add the section of Graph Traversal
  codes/java/chapter_graph/graph_adjacency_list.java
  codes/java/chapter_graph/graph_adjacency_matrix.java
  codes/java/chapter_graph/graph_bfs.java
  codes/java/chapter_graph/graph_dfs.java
  codes/java/chapter_graph/graph_traversal.java
  codes/java/include/Vertex.java
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_graph/graph.md
  docs/chapter_graph/graph_operations.md
  docs/chapter_graph/graph_traversal.assets/graph_bfs.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step1.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step10.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step11.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step2.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step3.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step4.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step5.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step6.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step7.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step8.png
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step9.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step1.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step10.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step11.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step2.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step3.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step4.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step5.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step6.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step7.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step8.png
  docs/chapter_graph/graph_traversal.assets/graph_dfs_step9.png
  docs/chapter_graph/graph_traversal.md
  docs/chapter_tree/binary_tree_traversal.md
  mkdocs.yml
Labels: writing

#348 feat: add ArrayDeque
  codes/c/chapter_stack_and_queue/array_queue.c
  codes/cpp/chapter_stack_and_queue/array_queue.cpp
  codes/csharp/chapter_stack_and_queue/array_queue.cs
  codes/go/chapter_stack_and_queue/array_queue.go
  codes/java/chapter_stack_and_queue/array_deque.java
  codes/java/chapter_stack_and_queue/array_queue.java
  codes/java/chapter_stack_and_queue/linkedlist_deque.java
  codes/javascript/chapter_stack_and_queue/array_queue.js
  codes/python/chapter_stack_and_queue/array_queue.py
  codes/swift/chapter_stack_and_queue/array_queue.swift
  codes/typescript/chapter_stack_and_queue/array_queue.ts
  codes/zig/chapter_stack_and_queue/array_queue.zig
  docs/chapter_stack_and_queue/deque.assets/array_deque.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_poll_first.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_poll_last.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_push_first.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_push_last.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_poll_first.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_poll_last.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_first.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_last.png
  docs/chapter_stack_and_queue/deque.md
Labels: writing

#366 add chapter_sorting by dart
  codes/c/chapter_sorting/bubble_sort.c
  codes/csharp/chapter_sorting/bubble_sort.cs
  codes/dart/chapter_sorting/bubble_sort.dart
  codes/dart/chapter_sorting/insertion_sort.dart
  codes/dart/chapter_sorting/merge_sort.dart
  codes/dart/chapter_sorting/quick_sort.dart
  codes/dart/chapter_sorting/radix_sort.dart
  codes/java/chapter_sorting/bubble_sort.java
Labels: coding

#379 refactor:Simplified lambda expressions for PriorityQueue in heap.md a…
  codes/java/chapter_heap/heap.java
  docs/chapter_heap/heap.md
Labels: coding, polishing

#378 feat: add Swift codes for graph_traversal article
  codes/swift/Package.swift
  codes/swift/chapter_graph/graph_adjacency_list.swift
  codes/swift/chapter_graph/graph_adjacency_list_target.swift
  codes/swift/chapter_graph/graph_bfs.swift
  codes/swift/chapter_graph/graph_dfs.swift
  codes/swift/utils/Vertex.swift
  docs/chapter_graph/graph_traversal.md
Labels: coding

#385 Update: Use function declarations instead of function expressions.
  codes/javascript/chapter_graph/graph_bfs.js
  codes/javascript/chapter_graph/graph_dfs.js
  codes/typescript/chapter_graph/graph_bfs.ts
  codes/typescript/chapter_graph/graph_dfs.ts
Labels: coding, polishing

#386 Fix: update the code comment
  codes/java/chapter_graph/graph_dfs.java
  codes/python/chapter_graph/graph_dfs.py
Labels: bug, coding

#384 Add linked list structure definition C language code in "linked_list. md"
  docs/chapter_array_and_linkedlist/linked_list.md
Labels: coding
