Repository krahets/hello-algo, pull requests merged in 2023-06, with the labels that each got.

#528 feat: Add the chapter cover images
  docs/assets/covers/chapter_array_and_linkedlist.jpg
  docs/assets/covers/chapter_backtracking.jpg
  docs/assets/covers/chapter_complexity_analysis.jpg
  docs/assets/covers/chapter_data_structure.jpg
  docs/assets/covers/chapter_dynamic_programming.jpg
  docs/assets/covers/chapter_graph.jpg
  docs/assets/covers/chapter_hashing.jpg
  docs/assets/covers/chapter_heap.jpg
  docs/assets/covers/chapter_introduction.jpg
  docs/assets/covers/chapter_preface.jpg
  docs/assets/covers/chapter_searching.jpg
  docs/assets/covers/chapter_sorting.jpg
  docs/assets/covers/chapter_stack_and_queue.jpg
  docs/assets/covers/chapter_tree.jpg
  docs/chapter_array_and_linkedlist/index.md
  docs/chapter_backtracking/index.md
  docs/chapter_computational_complexity/index.md
  docs/chapter_data_structure/index.md
  docs/chapter_graph/index.md
  docs/chapter_hashing/index.md
  docs/chapter_heap/index.md
  docs/chapter_introduction/index.md
  docs/chapter_preface/index.md
  docs/chapter_searching/index.md
  docs/chapter_sorting/index.md
  docs/chapter_stack_and_queue/index.md
  docs/chapter_tree/index.md
  mkdocs.yml
Labels: writing

#529 feat: Add Dart codes to the documents.
  codes/dart/chapter_array_and_linkedlist/array.dart
  codes/dart/chapter_array_and_linkedlist/linked_list.dart
  codes/dart/chapter_computational_complexity/worst_best_time_complexity.dart
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_backtracking/permutations_problem.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_graph/graph_operations.md
  docs/chapter_graph/graph_traversal.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/build_heap.md
  docs/chapter_heap/heap.md
  docs/chapter_preface/suggestions.md
  docs/chapter_searching/binary_search.md
  docs/chapter_searching/binary_search_edge.md
  docs/chapter_searching/replace_linear_by_hashing.md
  docs/chapter_sorting/bubble_sort.md
  docs/chapter_sorting/bucket_sort.md
  docs/chapter_sorting/counting_sort.md
  docs/chapter_sorting/heap_sort.md
  docs/chapter_sorting/insertion_sort.md
  docs/chapter_sorting/merge_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/radix_sort.md
  docs/chapter_sorting/selection_sort.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree.md
  docs/chapter_tree/binary_tree_traversal.md
Labels: writing

#545 Add JavaScript and TypeScript code of heap sort, selection sort and binary search edge and Fix the indentation of TS code
  codes/javascript/chapter_searching/binary_search_edge.js
  codes/javascript/chapter_sorting/heap_sort.js
  codes/javascript/chapter_sorting/selection_sort.js
  codes/typescript/chapter_backtracking/n_queens.ts
  codes/typescript/chapter_searching/binary_search_edge.ts
  codes/typescript/chapter_sorting/heap_sort.ts
  codes/typescript/chapter_sorting/selection_sort.ts
Labels: coding

#551 feat: Add the section of Top-K problem
  codes/cpp/chapter_heap/heap.cpp
  codes/cpp/chapter_heap/my_heap.cpp
  codes/cpp/chapter_heap/top_k.cpp
  codes/cpp/utils/print_utils.hpp
  codes/java/chapter_heap/top_k.java
  codes/python/chapter_heap/my_heap.py
  codes/python/chapter_heap/top_k.py
  docs/chapter_heap/build_heap.md
  docs/chapter_heap/top_k.assets/top_k_heap_step1.png
  docs/chapter_heap/top_k.assets/top_k_heap_step2.png
  docs/chapter_heap/top_k.assets/top_k_heap_step3.png
  docs/chapter_heap/top_k.assets/top_k_heap_step4.png
  docs/chapter_heap/top_k.assets/top_k_heap_step5.png
  docs/chapter_heap/top_k.assets/top_k_heap_step6.png
  docs/chapter_heap/top_k.assets/top_k_heap_step7.png
  docs/chapter_heap/top_k.assets/top_k_heap_step8.png
  docs/chapter_heap/top_k.assets/top_k_heap_step9.png
  docs/chapter_heap/top_k.assets/top_k_sorting.png
  docs/chapter_heap/top_k.assets/top_k_traversal.png
  docs/chapter_heap/top_k.md
  docs/index.md
  mkdocs.yml
Labels: coding, writing

#553 feat: Add the codes of hashmap
  README.md
  codes/c/chapter_hashing/array_hash_map.c
  codes/cpp/chapter_hashing/array_hash_map.cpp
  codes/cpp/chapter_hashing/hash_map_chaining.cpp
  codes/cpp/chapter_hashing/hash_map_open_addressing.cpp
  codes/csharp/chapter_graph/graph_adjacency_list.cs
  codes/csharp/chapter_hashing/array_hash_map.cs
  codes/dart/chapter_hashing/array_hash_map.dart
  codes/go/chapter_hashing/array_hash_map.go
  codes/go/chapter_hashing/array_hash_map_test.go
  codes/java/chapter_graph/graph_adjacency_list.java
  codes/java/chapter_hashing/array_hash_map.java
  codes/java/chapter_hashing/hash_map_chaining.java
  codes/java/chapter_hashing/hash_map_open_addressing.java
  codes/javascript/chapter_hashing/array_hash_map.js
  codes/python/chapter_hashing/array_hash_map.py
  codes/python/chapter_hashing/hash_map_chaining.py
  codes/python/chapter_hashing/hash_map_open_addressing.py
  codes/rust/chapter_hashing/array_hash_map.rs
  codes/swift/chapter_graph/graph_adjacency_list.swift
  codes/swift/chapter_hashing/array_hash_map.swift
  codes/typescript/chapter_hashing/array_hash_map.ts
  codes/zig/chapter_hashing/array_hash_map.zig
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_hashing/summary.md
  mkdocs.yml
Labels: coding, writing, polishing

#555 feat: Add the section of hash algorithm. Refactor the section of hash map.
  codes/cpp/chapter_graph/graph_adjacency_matrix.cpp
  codes/python/chapter_hashing/built_in_hash.py
  codes/python/chapter_hashing/simple_hash.py
  docs/chapter_hashing/hash_algorithm.assets/hash_collision_best_worst_condition.png
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/hash_map.assets/hash_table_reshash.png
  docs/chapter_hashing/hash_map.md
  mkdocs.yml
Labels: coding, writing

#558 feat: Add the section of subset sum problem
  codes/cpp/chapter_backtracking/subset_sum_i.cpp
  codes/cpp/chapter_backtracking/subset_sum_i_naive.cpp
  codes/cpp/chapter_backtracking/subset_sum_ii.cpp
  codes/java/chapter_backtracking/subset_sum_i.java
  codes/java/chapter_backtracking/subset_sum_i_naive.java
  codes/java/chapter_backtracking/subset_sum_ii.java
  codes/python/chapter_backtracking/subset_sum_i.py
  codes/python/chapter_backtracking/subset_sum_i_naive.py
  codes/python/chapter_backtracking/subset_sum_ii.py
  docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i.png
  docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i_naive.png
  docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i_pruning.png
  docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_ii.png
  docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_ii_repeat.png
  docs/chapter_backtracking/subset_sum_problem.md
  mkdocs.yml
Labels: coding, writing

#560 feat: Add Java and C++ code for the section hash algorithm
  codes/cpp/chapter_hashing/built_in_hash.cpp
  codes/cpp/chapter_hashing/simple_hash.cpp
  codes/java/chapter_hashing/built_in_hash.java
  codes/java/chapter_hashing/simple_hash.java
  codes/python/chapter_hashing/simple_hash.py
  docs/chapter_hashing/hash_algorithm.md
Labels: coding

#561 feat: Add the summary of backtracking
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_backtracking/subset_sum_problem.md
  docs/chapter_backtracking/summary.md
  mkdocs.yml
Labels: writing

#571 feat: add the section of the introduction to dynamic programming
  codes/cpp/CMakeLists.txt
  codes/cpp/chapter_dynamic_programming/CMakeLists.txt
  codes/cpp/chapter_dynamic_programming/climbing_stairs_backtrack.cpp
  codes/cpp/chapter_dynamic_programming/climbing_stairs_dfs.cpp
  codes/cpp/chapter_dynamic_programming/climbing_stairs_dfs_mem.cpp
  codes/cpp/chapter_dynamic_programming/climbing_stairs_dp.cpp
  codes/cpp/chapter_dynamic_programming/min_cost_climbing_stairs_dp.cpp
  codes/java/chapter_dynamic_programming/climbing_stairs_backtrack.java
  codes/java/chapter_dynamic_programming/climbing_stairs_dfs.java
  codes/java/chapter_dynamic_programming/climbing_stairs_dfs_mem.java
  codes/java/chapter_dynamic_programming/climbing_stairs_dp.java
  codes/java/chapter_dynamic_programming/min_cost_climbing_stairs_dp.java
  codes/python/chapter_dynamic_programming/climbing_stairs_backtrack.py
  codes/python/chapter_dynamic_programming/climbing_stairs_dfs.py
  codes/python/chapter_dynamic_programming/climbing_stairs_dfs_mem.py
  codes/python/chapter_dynamic_programming/climbing_stairs_dp.py
  codes/python/chapter_dynamic_programming/min_cost_climbing_stairs_dp.py
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_dynamic_programming/index.md
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_dfs_memo_tree.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_dfs_tree.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_dp.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_example.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/climbing_stairs_state_transfer.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/min_cost_cs_dp.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.assets/min_cost_cs_example.png
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
  mkdocs.yml
Labels: coding, writing
