Repository krahets/hello-algo, pull requests merged in 2023-09, with the labels that each got.

#717 feat: add Swift codes for iteration_and_recursion article
  codes/swift/Package.swift
  codes/swift/chapter_computational_complexity/iteration.swift
  codes/swift/chapter_computational_complexity/recursion.swift
Labels: coding

#716 refactor: remove buildTree
  codes/swift/chapter_tree/binary_search_tree.swift
Labels: bug, coding

#715 Fix binary_search_tree TS code and update JS code style
  codes/javascript/chapter_tree/binary_search_tree.js
  codes/typescript/chapter_tree/avl_tree.ts
  codes/typescript/chapter_tree/binary_search_tree.ts
Labels: coding

#721 refactor: sort the coding languages by applications.
  codes/swift/chapter_greedy/fractional_knapsack.swift
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_backtracking/permutations_problem.md
  docs/chapter_backtracking/subset_sum_problem.md
  docs/chapter_computational_complexity/iteration_and_recursion.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_divide_and_conquer/binary_search_recur.md
  docs/chapter_divide_and_conquer/build_binary_tree_problem.md
  docs/chapter_divide_and_conquer/hanota_problem.md
  docs/chapter_dynamic_programming/dp_problem_features.md
  docs/chapter_dynamic_programming/dp_solution_pipeline.md
  docs/chapter_dynamic_programming/edit_distance_problem.md
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
  docs/chapter_dynamic_programming/knapsack_problem.md
  docs/chapter_dynamic_programming/unbounded_knapsack_problem.md
  docs/chapter_graph/graph_operations.md
  docs/chapter_graph/graph_traversal.md
  docs/chapter_greedy/fractional_knapsack_problem.md
  docs/chapter_greedy/greedy_algorithm.md
  docs/chapter_greedy/max_capacity_problem.md
  docs/chapter_greedy/max_product_cutting_problem.md
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/build_heap.md
  docs/chapter_heap/heap.md
  docs/chapter_heap/top_k.md
  docs/chapter_preface/suggestions.md
  docs/chapter_searching/binary_search.md
  docs/chapter_searching/binary_search_edge.md
  docs/chapter_searching/binary_search_insertion.md
  docs/chapter_searching/replace_linear_by_hashing.md
  docs/chapter_sorting/bubble_sort.md
  docs/chapter_sorting/bucket_sort.md
  docs/chapter_sorting/counting_sort.md
  docs/chapter_sorting/heap_sort.md
  docs/chapter_sorting/insertion_sort.md
  docs/chapter_sorting/merge_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/radix_sort.md
  docs/chapter_sorting/selection_sort.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree.md
  docs/chapter_tree/binary_tree_traversal.md
Labels: coding, writing

#724 feat: add rust codes for simple_hash
  codes/rust/Cargo.toml
  codes/rust/chapter_hashing/simple_hash.rs
Labels: coding

#726 feat: add C code for the section of greedy algorithm
  codes/c/CMakeLists.txt
  codes/c/chapter_greedy/CMakeLists.txt
  codes/c/chapter_greedy/coin_change_greedy.c
Labels: coding

#732 Fix `my_heap.c` build error
  codes/c/chapter_heap/my_heap.c
Labels: bug, coding

#729 Fix print error
  codes/cpp/chapter_greedy/coin_change_greedy.cpp
Labels: bug, coding

#741 style: Make the picture not glare in dark theme
  docs/stylesheets/extra.css
Labels: enhancement

#747 Fix `insert` function in `mylist.c`
  codes/c/chapter_array_and_linkedlist/my_list.c
Labels: bug, coding

#739 fix: modify a function name in array_stack.js(ts) and array_queue.js(ts)
  codes/javascript/chapter_stack_and_queue/array_queue.js
  codes/javascript/chapter_stack_and_queue/array_stack.js
  codes/typescript/chapter_stack_and_queue/array_queue.ts
  codes/typescript/chapter_stack_and_queue/array_stack.ts
Labels: bug, coding

#746 fix:: Sync the while loop in iteration.cs with other languages
  codes/csharp/chapter_computational_complexity/iteration.cs
Labels: bug, coding

#767 follow PEP585 typing
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
Labels: bug, coding

#727 fix: Update hash_map_open_addressing.java
  codes/java/chapter_hashing/hash_map_open_addressing.java
Labels: bug, coding

#776 refactor: new hash_map_open_addressing implementation
  codes/cpp/chapter_hashing/hash_map_open_addressing.cpp
  codes/python/chapter_hashing/hash_map_open_addressing.py
  docs/chapter_hashing/hash_collision.assets/hash_table_open_addressing_deletion.png
  docs/chapter_hashing/hash_collision.md
Labels: bug, coding

#763 feat: add previous and next button in content.html
  .gitignore
  Dockerfile
  docs/overrides/partials/content.html
Labels: enhancement

#784 Fix JS and TS sort bugs for subset_sum
  codes/javascript/chapter_backtracking/subset_sum_i.js
  codes/javascript/chapter_backtracking/subset_sum_ii.js
  codes/typescript/chapter_backtracking/subset_sum_i.ts
  codes/typescript/chapter_backtracking/subset_sum_ii.ts
Labels: bug, coding

#785 fix(JS, TS): chapter_sorting QuickSortMedian and QuickSortTailCall exa…
  codes/javascript/chapter_sorting/quick_sort.js
  codes/typescript/chapter_sorting/quick_sort.ts
Labels: coding

#787 refactor: update the hash_map_open_addressing rust codes to synchronize wi…
  codes/rust/chapter_hashing/array_hash_map.rs
  codes/rust/chapter_hashing/hash_map_open_addressing.rs
Labels: coding

#772 Update dp_problem_features.md
  docs/chapter_dynamic_programming/dp_problem_features.md
Labels: writing, polishing

#802 feat(dart): add forLoopRecur and update HashMapOpenAddressing
  codes/dart/chapter_computational_complexity/recursion.dart
  codes/dart/chapter_hashing/hash_map_chaining.dart
  codes/dart/chapter_hashing/hash_map_open_addressing.dart
Labels: coding

#801 fix a typo in graph_traversal.md
  docs/chapter_graph/graph_traversal.md
Labels: bug, writing

#771 feat: Add C code for the section of intro to DP
  codes/c/chapter_dynamic_programming/climbing_stairs_backtrack.c
  codes/c/chapter_dynamic_programming/climbing_stairs_dfs.c
  codes/c/chapter_dynamic_programming/climbing_stairs_dfs_mem.c
  codes/c/chapter_dynamic_programming/climbing_stairs_dp.c
Labels: coding

#808 Update deque.md
  docs/chapter_stack_and_queue/deque.md
Labels: writing, polishing

#811 fix: the rust variable should have a snake case name
  codes/rust/chapter_divide_and_conquer/build_tree.rs
Labels: bug, coding
