Repository krahets/hello-algo, pull requests merged in 2023-12, with the labels that each got.

#979 feat: Update the assets and GIF animations.
  README.md
  docs/chapter_preface/about_the_book.md
  docs/index.assets/animation.gif
  docs/index.assets/animation_dark.gif
  docs/index.assets/btn_download_code_dark.png
  docs/index.assets/btn_download_code_light.png
  docs/index.assets/btn_download_pdf.svg
  docs/index.assets/btn_download_pdf_dark.png
  docs/index.assets/btn_download_pdf_dark.svg
  docs/index.assets/btn_download_pdf_light.png
  docs/index.assets/btn_read_online.svg
  docs/index.assets/btn_read_online_dark.png
  docs/index.assets/btn_read_online_dark.svg
  docs/index.assets/btn_read_online_light.png
  docs/index.assets/comment.gif
  docs/index.assets/running_code.gif
  docs/index.assets/running_code_dark.gif
  docs/index.md
Labels: enhancement

#981 Several enhancements and bug fixes
  .gitignore
  docs/chapter_appendix/installation.assets/vscode_extension_installation.png
  docs/chapter_appendix/installation.assets/vscode_installation.png
  docs/chapter_appendix/installation.md
  docs/chapter_array_and_linkedlist/ram_and_cache.assets/storage_pyramid.png
  docs/index.assets/btn_download_pdf.svg
  docs/index.assets/btn_download_pdf_dark.svg
  docs/index.assets/btn_read_online.svg
  docs/index.assets/btn_read_online_dark.svg
  docs/index.md
  mkdocs.yml
  overrides/partials/.gitignore
  overrides/partials/LICENSE
  overrides/partials/actions.html
  overrides/partials/content.html
  overrides/stylesheets/extra.css
Labels: enhancement, documents

#953 translation: chapter_computational_complexity/summary to en
  docs-en/chapter_computational_complexity/summary.md
Labels: translation, documents

#984 Several bug fixes
  docs/chapter_searching/binary_search.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/radix_sort.md
  docs/chapter_sorting/summary.md
  mkdocs.yml
  overrides/javascripts/mathjax.js
Labels: bug, code, documents

#962 translation: chapter_introduction/what_is_dsa.md
  docs-en/chapter_introduction/what_is_dsa.md
Labels: translation, documents

#987 Revised the book
  codes/python/modules/__init__.py
  docs/chapter_appendix/terminology.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_array_and_linkedlist/ram_and_cache.md
  docs/chapter_array_and_linkedlist/summary.md
  docs/chapter_computational_complexity/iteration_and_recursion.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_data_structure/character_encoding.md
  docs/chapter_data_structure/classification_of_data_structure.md
  docs/chapter_data_structure/number_encoding.md
  docs/chapter_data_structure/summary.md
  docs/chapter_dynamic_programming/dp_problem_features.md
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/summary.md
  docs/chapter_heap/build_heap.md
  docs/chapter_stack_and_queue/summary.md
  docs/chapter_tree/avl_tree.md
Labels: bug, code, documents, embellishment

#991 Several bug fixes and improvements
  docs/chapter_appendix/installation.md
  docs/chapter_appendix/terminology.md
  docs/index.md
Labels: enhancement, documents

#992 fix(go): fix go code , refer to @joengtou @wcig @shenjq
  codes/go/chapter_backtracking/preorder_traversal_ii_compact.go
  codes/go/chapter_hashing/hash_map_chaining.go
  codes/go/chapter_hashing/hash_map_open_addressing.go
Labels: bug, code

#963 translation: chapter_introduction/summary.md
  docs-en/chapter_introduction/summary.md
Labels: translation, documents

#964 translation: Update README.md
  README.md
Labels: translation, documents

#970 translation: update space_complexity.md
  docs-en/chapter_computational_complexity/space_complexity.md
Labels: translation, documents

#971 translation: Update chapter_introduction/index.md
  docs-en/chapter_introduction/index.md
Labels: translation, documents

#980 translation: Update chapter_data_structure/classification_of_data_structure.md
  docs-en/chapter_data_structure/classification_of_data_structure.md
Labels: translation, documents

#972 translation: Update chapter_introduction/algorithms_are_everywhere.md
  docs-en/chapter_introduction/algorithms_are_everywhere.md
Labels: translation, documents

#1002 Several improvements
  README.md
  codes/c/chapter_array_and_linkedlist/linked_list.c
  docs-en/chapter_preface/about_the_book.md
  docs-en/index.assets/animation.gif
  docs-en/index.assets/animation_dark.gif
  docs-en/index.assets/btn_chinese_edition.svg
  docs-en/index.assets/btn_chinese_edition_dark.svg
  docs-en/index.assets/btn_download_pdf.svg
  docs-en/index.assets/btn_download_pdf_dark.svg
  docs-en/index.assets/btn_read_online.svg
  docs-en/index.assets/btn_read_online_dark.svg
  docs-en/index.assets/comment.gif
  docs-en/index.assets/running_code.gif
  docs-en/index.assets/running_code_dark.gif
  docs-en/index.md
  docs/index.assets/btn_download_pdf.svg
  docs/index.assets/btn_download_pdf_dark.svg
  docs/index.assets/btn_english_edition.svg
  docs/index.assets/btn_english_edition_dark.svg
  docs/index.assets/btn_read_online.svg
  docs/index.assets/btn_read_online_dark.svg
  mkdocs-en.yml
Labels: documents, embellishment

#1001 translation: Update the complexity analysis chapter to the main branch
  docs-en/chapter_computational_complexity/index.md
  docs-en/chapter_computational_complexity/iteration_and_recursion.md
  docs-en/chapter_computational_complexity/performance_evaluation.md
  docs-en/chapter_computational_complexity/space_complexity.md
  docs-en/chapter_computational_complexity/summary.md
  docs-en/chapter_computational_complexity/time_complexity.md
  docs-en/chapter_introduction/what_is_dsa.md
Labels: translation, documents

#998 translation: Update algorithms_are_everywhere.md
  docs-en/chapter_introduction/algorithms_are_everywhere.md
Labels: translation, documents

#1003 translation: refine preface index and about_the_book (duplicates from #997)
  docs-en/chapter_preface/about_the_book.md
  docs-en/chapter_preface/index.md
Labels: translation, documents

#1000 translation: Update chapter_data_structure/index.md
  docs-en/chapter_data_structure/index.md
Labels: translation, documents

#1006 Fix the issue of the comment 7938404
  codes/rust/chapter_searching/binary_search.rs
Labels: bug, code

#1007 translation: Add the translation of the data structure chapter
  docs-en/chapter_data_structure/basic_data_types.md
  docs-en/chapter_data_structure/character_encoding.assets/ascii_table.png
  docs-en/chapter_data_structure/character_encoding.assets/unicode_hello_algo.png
  docs-en/chapter_data_structure/character_encoding.assets/utf-8_hello_algo.png
  docs-en/chapter_data_structure/character_encoding.md
  docs-en/chapter_data_structure/classification_of_data_structure.md
  docs-en/chapter_data_structure/index.md
  docs-en/chapter_data_structure/number_encoding.assets/1s_2s_complement.png
  docs-en/chapter_data_structure/number_encoding.assets/ieee_754_float.png
  docs-en/chapter_data_structure/number_encoding.md
  docs-en/chapter_data_structure/summary.md
  docs-en/chapter_preface/suggestions.md
  docs/chapter_data_structure/character_encoding.md
  mkdocs-en.yml
Labels: translation, documents

#1008 translation: Add the initial translation of the array and linked list chapter
  docs-en/chapter_array_and_linkedlist/array.assets/array_definition.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_insert_element.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_memory_location_calculation.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_remove_element.png
  docs-en/chapter_array_and_linkedlist/array.md
  docs-en/chapter_array_and_linkedlist/index.md
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_common_types.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_definition.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_insert_node.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_remove_node.png
  docs-en/chapter_array_and_linkedlist/linked_list.md
  docs-en/chapter_array_and_linkedlist/list.md
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/computer_storage_devices.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/storage_pyramid.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.md
  docs-en/chapter_array_and_linkedlist/summary.md
  docs-en/chapter_data_structure/basic_data_types.md
Labels: translation, documents

#1011 fix(csharp): unified array statement
  docs-en/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/array.md
Labels: bug, code
