Repository krahets/hello-algo, pull requests merged in 2023-11, with the labels that each got.

#909 Update README
  README.md
  docs/index.assets/hello_algo_header.png
Labels: documents

#911 Fix Python build check script.
  .github/workflows/python.yml
  codes/python/build.py
  codes/python/test_all.py
  docs/chapter_appendix/installation.md
Labels: bug

#913 fix: Fix EN translation of chapter_appendix/terminology.md
  docs-en/chapter_appendix/terminology.md
Labels: bug, documents

#918 Update README.md
  README.md
Labels: documents, embellishment

#919 Several bug fixes
  README.md
  docs/chapter_preface/about_the_book.md
  docs/index.md
Labels: bug, documents

#924 Update the logo and favicon
  docs/chapter_computational_complexity/iteration_and_recursion.md
  mkdocs.yml
  overrides/assets/images/favicon.png
  overrides/assets/images/logo.svg
Labels: documents, embellishment

#926 Update basic_data_types.md and reduce size of assembling_blocks.png
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_introduction/what_is_dsa.assets/assembling_blocks.jpg
  docs/chapter_introduction/what_is_dsa.assets/assembling_blocks.png
  docs/chapter_introduction/what_is_dsa.md
Labels: documents

#927 feat: Add Docker for code debugging
  Dockerfile
  codes/Dockerfile
  codes/docker-compose.yml
  docker-compose.yml
Labels: enhancement

#929 feat: add csharp sdk to dockerfile
  codes/Dockerfile
  codes/docker-compose.yml
Labels: enhancement

#931 Unsize type must be greater than or equal to 0
  codes/rust/chapter_array_and_linkedlist/my_list.rs
Labels: bug, code

#935 fix: Update linked_list.md
  docs/chapter_array_and_linkedlist/linked_list.md
Labels: bug, code

#932 translation: Refined the automated translation of README
  README.md
  docs-en/index.md
  mkdocs-en.yml
Labels: translation, documents

#940 translate: Embellish chapter_computational_complexity/index.md
  docs-en/chapter_computational_complexity/index.md
Labels: translation

#942 Use Vec.last() method to access the top item of stack.
  codes/rust/chapter_stack_and_queue/stack.rs
  docs/chapter_stack_and_queue/stack.md
Labels: code, embellishment

#943 translation: Update chapter_computational_complexity/performance_evaluation.md
  docs-en/chapter_computational_complexity/performance_evaluation.md
Labels: translation, documents

#946 fix(Dart): Avoid using num as a variable name
  codes/dart/chapter_array_and_linkedlist/array.dart
  codes/dart/chapter_array_and_linkedlist/list.dart
  codes/dart/chapter_array_and_linkedlist/my_list.dart
  codes/dart/chapter_computational_complexity/time_complexity.dart
  codes/dart/chapter_hashing/built_in_hash.dart
  codes/dart/chapter_sorting/bucket_sort.dart
  codes/dart/chapter_sorting/counting_sort.dart
  codes/dart/chapter_sorting/radix_sort.dart
  codes/dart/chapter_stack_and_queue/array_deque.dart
  codes/dart/chapter_stack_and_queue/array_queue.dart
  codes/dart/chapter_stack_and_queue/array_stack.dart
  codes/dart/chapter_stack_and_queue/linkedlist_deque.dart
  codes/dart/chapter_stack_and_queue/linkedlist_queue.dart
  codes/dart/chapter_stack_and_queue/linkedlist_stack.dart
  codes/dart/chapter_tree/binary_search_tree.dart
Labels: bug, code

#948 feat: Add auto-build-and-test workflow for C and C++
  .github/workflows/c.yml
  .github/workflows/cpp.yml
Labels: enhancement

#949 fix: Update C code for compatibility with the MSVC compiler
  codes/c/chapter_array_and_linkedlist/array.c
  codes/c/chapter_backtracking/preorder_traversal_i_compact.c
  codes/c/chapter_backtracking/preorder_traversal_ii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_template.c
  codes/c/chapter_dynamic_programming/climbing_stairs_constraint_dp.c
  codes/c/chapter_dynamic_programming/coin_change.c
  codes/c/chapter_dynamic_programming/coin_change_ii.c
  codes/c/chapter_dynamic_programming/edit_distance.c
  codes/c/chapter_dynamic_programming/knapsack.c
  codes/c/chapter_dynamic_programming/min_cost_climbing_stairs_dp.c
  codes/c/chapter_dynamic_programming/min_path_sum.c
  codes/c/chapter_dynamic_programming/unbounded_knapsack.c
  codes/c/chapter_greedy/CMakeLists.txt
  codes/c/chapter_greedy/max_capacity.c
  codes/c/chapter_heap/top_k.c
  codes/c/chapter_stack_and_queue/array_deque.c
  codes/c/chapter_stack_and_queue/array_queue.c
  codes/c/chapter_stack_and_queue/linkedlist_deque.c
  codes/c/chapter_stack_and_queue/linkedlist_queue.c
  codes/c/utils/print_util.h
  codes/cpp/chapter_backtracking/preorder_traversal_i_compact.cpp
  codes/cpp/chapter_backtracking/preorder_traversal_ii_compact.cpp
Labels: bug, code

#951 Fix the type annotation in Rust
  docs/chapter_data_structure/basic_data_types.md
Labels: bug, code

#952 feat: add rust workflow
  .github/workflows/rust.yml
Labels: enhancement, code

#955 fix: Update time_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, documents

#947 fix: Initialize go empty slice
  docs/chapter_array_and_linkedlist/list.md
Labels: bug, code

#961 fix: Use .equals() to compare two strings in Java
  codes/java/chapter_tree/array_binary_tree.java
Labels: bug, code

#954 translation: Update terminology and improve readability in preface summary
  docs-en/chapter_preface/summary.md
Labels: translation, documents

#960 Simplify the code in array.swift
  codes/swift/chapter_array_and_linkedlist/array.swift
Labels: code, embellishment

#968 fix: bug fixes for array_hash_map.c and counting_sort.c
  codes/c/chapter_hashing/array_hash_map.c
  codes/c/chapter_sorting/counting_sort.c
Labels: bug, code

#973 fix: Several code bug fixes
  codes/c/chapter_hashing/hash_map_chaining.c
  codes/c/chapter_sorting/counting_sort.c
  codes/c/chapter_sorting/quick_sort.c
  codes/go/chapter_hashing/hash_map_open_addressing.go
Labels: bug, code
