Repository krahets/hello-algo, pull requests merged in 2023-05, with the labels that each got.

#480 feat: add Swift codes for backtracking_algorithm article
  codes/swift/Package.swift
  codes/swift/chapter_backtracking/preorder_traversal_i_compact.swift
  codes/swift/chapter_backtracking/preorder_traversal_ii_compact.swift
  codes/swift/chapter_backtracking/preorder_traversal_iii_compact.swift
  codes/swift/chapter_backtracking/preorder_traversal_iii_template.swift
  codes/swift/chapter_tree/avl_tree.swift
  codes/swift/chapter_tree/binary_search_tree.swift
Labels: coding

#483 feat: Add the section of n queens problem
  codes/cpp/chapter_backtracking/n_queens.cpp
  codes/java/chapter_backtracking/n_queens.java
  codes/python/chapter_backtracking/n_queens.py
  docs/chapter_backtracking/n_queens_problem.assets/n_queens_cols_diagonals.png
  docs/chapter_backtracking/n_queens_problem.assets/n_queens_constraints.png
  docs/chapter_backtracking/n_queens_problem.assets/n_queens_placing.png
  docs/chapter_backtracking/n_queens_problem.assets/solution_4_queens.png
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_backtracking/permutations_problem.md
  mkdocs.yml
Labels: coding, writing

#485 feat(csharp/backtracking): add csharp code in n queens
  codes/csharp/chapter_backtracking/n_queens.cs
Labels: coding

#494 Add JavaScript and TypeScript code of permutations and n_queens (Chapter of Backtracking)
  codes/javascript/chapter_backtracking/n_queens.js
  codes/javascript/chapter_backtracking/permutations_i.js
  codes/javascript/chapter_backtracking/permutations_ii.js
  codes/typescript/chapter_backtracking/n_queens.ts
  codes/typescript/chapter_backtracking/permutations_i.ts
  codes/typescript/chapter_backtracking/permutations_ii.ts
Labels: coding

#491 Fix function call error and null safety
  codes/dart/chapter_tree/avl_tree.dart
  codes/dart/chapter_tree/binary_search_tree.dart
Labels: bug

#496 fix:range issue
  codes/go/chapter_sorting/counting_sort.go
Labels: bug

#508 feat: Add the section of binary search edge.
  codes/cpp/chapter_binary_search/binary_search_edge.cpp
  codes/java/chapter_binary_search/binary_search_edge.java
  codes/python/chapter_binary_search/binary_search.py
  codes/python/chapter_binary_search/binary_search_edge.py
  docs/chapter_binary_search/binary_search.md
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_naive.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step1.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step2.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step3.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step4.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step5.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step6.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step7.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_edge_step8.png
  docs/chapter_binary_search/binary_search_edge.assets/binary_search_left_right_edge.png
  docs/chapter_binary_search/binary_search_edge.md
  mkdocs.yml
Labels: coding, writing

#513 feat: Add the section of selection sort.
  codes/cpp/chapter_sorting/selection_sort.cpp
  codes/java/chapter_sorting/selection_sort.java
  codes/python/chapter_sorting/selection_sort.py
  docs/chapter_sorting/selection_sort.assets/selection_sort_step1.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step10.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step11.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step2.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step3.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step4.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step5.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step6.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step7.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step8.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_step9.png
  docs/chapter_sorting/selection_sort.assets/selection_sort_unstable.png
  docs/chapter_sorting/selection_sort.md
  mkdocs.yml
Labels: coding, writing

#516 feat: Add the section of heap sort.
  codes/cpp/chapter_sorting/CMakeLists.txt
  codes/cpp/chapter_sorting/heap_sort.cpp
  codes/java/chapter_sorting/heap_sort.java
  codes/python/chapter_sorting/heap_sort.py
  docs/chapter_sorting/heap_sort.assets/heap_sort_step1.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step10.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step11.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step12.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step2.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step3.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step4.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step5.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step6.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step7.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step8.png
  docs/chapter_sorting/heap_sort.assets/heap_sort_step9.png
  docs/chapter_sorting/heap_sort.md
  mkdocs.yml
Labels: coding, writing

#521 feat(sort/search): support heap/selection_sort/binary_search_edge in go code
  codes/go/chapter_searching/binary_search_edge.go
  codes/go/chapter_searching/binary_search_test.go
  codes/go/chapter_sorting/heap_sort.go
  codes/go/chapter_sorting/heap_sort_test.go
  codes/go/chapter_sorting/selection_sort.go
  codes/go/chapter_sorting/selection_sort_test.go
Labels: coding

#522 Update Dart code to output same as Java
  codes/dart/chapter_array_and_linkedlist/array.dart
  codes/dart/chapter_array_and_linkedlist/linked_list.dart
  codes/dart/chapter_array_and_linkedlist/list.dart
  codes/dart/chapter_array_and_linkedlist/my_list.dart
  codes/dart/chapter_computational_complexity/space_complexity.dart
  codes/dart/chapter_graph/graph_adjacency_matrix.dart
  codes/dart/chapter_heap/my_heap.dart
  codes/dart/chapter_sorting/bucket_sort.dart
  codes/dart/chapter_stack_and_queue/array_deque.dart
  codes/dart/chapter_stack_and_queue/array_queue.dart
  codes/dart/chapter_stack_and_queue/deque.dart
  codes/dart/chapter_stack_and_queue/queue.dart
  codes/dart/chapter_stack_and_queue/stack.dart
  codes/dart/utils/print_util.dart
Labels: bug, coding
