Repository krahets/hello-algo, pull requests merged in 2023-04, with the labels that each got.

#448 feat: add dart code for chapter_tree
  codes/dart/chapter_tree/avl_tree.dart
  codes/dart/chapter_tree/binary_search_tree.dart
  codes/dart/chapter_tree/binary_tree.dart
  codes/dart/chapter_tree/binary_tree_bfs.dart
  codes/dart/chapter_tree/binary_tree_dfs.dart
  codes/dart/utils/tree_node.dart
Labels: coding

#453 refactor: Format python codes with black
  codes/python/chapter_array_and_linkedlist/array.py
  codes/python/chapter_array_and_linkedlist/linked_list.py
  codes/python/chapter_array_and_linkedlist/list.py
  codes/python/chapter_array_and_linkedlist/my_list.py
  codes/python/chapter_computational_complexity/leetcode_two_sum.py
  codes/python/chapter_computational_complexity/space_complexity.py
  codes/python/chapter_computational_complexity/time_complexity.py
  codes/python/chapter_computational_complexity/worst_best_time_complexity.py
  codes/python/chapter_graph/graph_adjacency_list.py
  codes/python/chapter_graph/graph_adjacency_matrix.py
  codes/python/chapter_graph/graph_bfs.py
  codes/python/chapter_graph/graph_dfs.py
  codes/python/chapter_hashing/array_hash_map.py
  codes/python/chapter_hashing/hash_map.py
  codes/python/chapter_heap/heap.py
  codes/python/chapter_heap/my_heap.py
  codes/python/chapter_searching/binary_search.py
  codes/python/chapter_searching/hashing_search.py
  codes/python/chapter_searching/linear_search.py
  codes/python/chapter_sorting/bubble_sort.py
  codes/python/chapter_sorting/bucket_sort.py
  codes/python/chapter_sorting/counting_sort.py
  codes/python/chapter_sorting/insertion_sort.py
  codes/python/chapter_sorting/merge_sort.py
  codes/python/chapter_sorting/quick_sort.py
  codes/python/chapter_sorting/radix_sort.py
  codes/python/chapter_stack_and_queue/array_deque.py
  codes/python/chapter_stack_and_queue/array_queue.py
  codes/python/chapter_stack_and_queue/array_stack.py
  codes/python/chapter_stack_and_queue/deque.py
  codes/python/chapter_stack_and_queue/linkedlist_deque.py
  codes/python/chapter_stack_and_queue/linkedlist_queue.py
  codes/python/chapter_stack_and_queue/linkedlist_stack.py
  codes/python/chapter_stack_and_queue/queue.py
  codes/python/chapter_stack_and_queue/stack.py
  codes/python/chapter_tree/avl_tree.py
  codes/python/chapter_tree/binary_search_tree.py
  codes/python/chapter_tree/binary_tree.py
  codes/python/chapter_tree/binary_tree_bfs.py
  codes/python/chapter_tree/binary_tree_dfs.py
  codes/python/modules/__init__.py
  codes/python/modules/binary_tree.py
  codes/python/modules/linked_list.py
  codes/python/modules/print_util.py
  codes/python/modules/vertex.py
Labels: coding, polishing

#459 feat: Add the chapter of backtracking.
  codes/java/chapter_backtracking/backtrack_find_constrained_paths.java
  codes/java/chapter_backtracking/preorder_find_constrained_paths.java
  codes/java/chapter_backtracking/preorder_find_nodes.java
  codes/java/chapter_backtracking/preorder_find_paths.java
  codes/python/chapter_backtracking/backtrack_find_constrained_paths.py
  codes/python/chapter_backtracking/preorder_find_constrained_paths.py
  codes/python/chapter_backtracking/preorder_find_nodes.py
  codes/python/chapter_backtracking/preorder_find_paths.py
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_constrained_paths.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_nodes.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step1.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step10.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step11.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step2.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step3.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step4.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step5.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step6.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step7.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step8.png
  docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step9.png
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_sorting/sorting_algorithm.assets/sorting_examples.png
  docs/chapter_sorting/sorting_algorithm.md
  mkdocs.yml
Labels: coding, writing

#464 refactor: Many changes related to searching algorithm
  codes/c/CMakeLists.txt
  codes/c/chapter_binary_search/CMakeLists.txt
  codes/c/chapter_binary_search/binary_search.c
  codes/c/chapter_computational_complexity/CMakeLists.txt
  codes/c/chapter_searching/CMakeLists.txt
  codes/c/chapter_searching/leetcode_two_sum.c
  codes/cpp/CMakeLists.txt
  codes/cpp/chapter_binary_search/CMakeLists.txt
  codes/cpp/chapter_binary_search/binary_search.cpp
  codes/cpp/chapter_computational_complexity/CMakeLists.txt
  codes/cpp/chapter_searching/CMakeLists.txt
  codes/cpp/chapter_searching/leetcode_two_sum.cpp
  codes/csharp/chapter_binary_search/binary_search.cs
  codes/csharp/chapter_searching/leetcode_two_sum.cs
  codes/go/chapter_binary_search/binary_search.go
  codes/go/chapter_binary_search/binary_search_test.go
  codes/go/chapter_searching/leetcode_two_sum.go
  codes/go/chapter_searching/leetcode_two_sum_test.go
  codes/java/chapter_backtracking/backtrack_find_constrained_paths.java
  codes/java/chapter_backtracking/preorder_find_constrained_paths.java
  codes/java/chapter_backtracking/preorder_find_nodes.java
  codes/java/chapter_backtracking/preorder_find_paths.java
  codes/java/chapter_binary_search/binary_search.java
  codes/java/chapter_searching/leetcode_two_sum.java
  codes/javascript/chapter_binary_search/binary_search.js
  codes/javascript/chapter_searching/leetcode_two_sum.js
  codes/python/chapter_binary_search/binary_search.py
  codes/python/chapter_searching/leetcode_two_sum.py
  codes/rust/chapter_binary_search/binary_search.rs
  codes/swift/chapter_binary_search/binary_search.swift
  codes/swift/chapter_searching/leetcode_two_sum.swift
  codes/typescript/chapter_binary_search/binary_search.ts
  codes/typescript/chapter_searching/leetcode_two_sum.ts
  codes/zig/chapter_binary_search/binary_search.zig
  codes/zig/chapter_searching/leetcode_two_sum.zig
  docs/chapter_binary_search/binary_search.assets/binary_search_step1.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step2.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step3.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step4.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step5.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step6.png
  docs/chapter_binary_search/binary_search.assets/binary_search_step7.png
  docs/chapter_binary_search/binary_search.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/summary.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_searching/hashing_search.assets/hash_search_listnode.png
  docs/chapter_searching/hashing_search.md
  docs/chapter_searching/linear_search.md
  docs/chapter_searching/replace_linear_by_hashing.assets/hashing_search.png
  docs/chapter_searching/replace_linear_by_hashing.assets/linear_search.png
  docs/chapter_searching/replace_linear_by_hashing.md
  docs/chapter_searching/searching_algorithm_revisited.assets/searching_algorithms.png
  docs/chapter_searching/searching_algorithm_revisited.md
  docs/chapter_searching/summary.md
  docs/chapter_tree/binary_search_tree.md
  mkdocs.yml
Labels: enhancement, coding, writing

#469 feat: Publish the C codes to the docs.
  codes/c/chapter_array_and_linkedlist/array.c
  codes/c/chapter_array_and_linkedlist/linked_list.c
  codes/c/chapter_array_and_linkedlist/my_list.c
  codes/c/chapter_computational_complexity/space_complexity.c
  codes/c/chapter_heap/my_heap.c
  codes/c/chapter_sorting/quick_sort.c
  codes/c/chapter_stack_and_queue/array_deque.c
  codes/c/chapter_stack_and_queue/array_queue.c
  codes/c/chapter_stack_and_queue/array_stack.c
  codes/c/chapter_stack_and_queue/linkedlist_deque.c
  codes/c/chapter_stack_and_queue/linkedlist_queue.c
  codes/c/chapter_stack_and_queue/linkedlist_stack.c
  codes/c/chapter_tree/avl_tree.c
  codes/c/include/tree_node.h
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_binary_search/binary_search.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/heap.md
  docs/chapter_sorting/merge_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree.md
Labels: coding, polishing

#471 refactor: add/refactor method in include, simplified print code
  codes/csharp/chapter_backtracking/backtrack_find_constrained_paths.cs
  codes/csharp/chapter_backtracking/preorder_find_constrained_paths.cs
  codes/csharp/chapter_backtracking/preorder_find_nodes.cs
  codes/csharp/chapter_backtracking/preorder_find_paths.cs
  codes/csharp/chapter_computational_complexity/space_complexity.cs
  codes/csharp/chapter_graph/graph_adjacency_list.cs
  codes/csharp/chapter_graph/graph_adjacency_matrix.cs
  codes/csharp/chapter_graph/graph_bfs.cs
  codes/csharp/chapter_graph/graph_dfs.cs
  codes/csharp/chapter_hashing/array_hash_map.cs
  codes/csharp/chapter_hashing/hash_map.cs
  codes/csharp/chapter_heap/heap.cs
  codes/csharp/chapter_heap/my_heap.cs
  codes/csharp/chapter_stack_and_queue/array_stack.cs
  codes/csharp/chapter_stack_and_queue/deque.cs
  codes/csharp/chapter_stack_and_queue/linkedlist_queue.cs
  codes/csharp/chapter_stack_and_queue/linkedlist_stack.cs
  codes/csharp/chapter_stack_and_queue/queue.cs
  codes/csharp/chapter_stack_and_queue/stack.cs
  codes/csharp/chapter_tree/binary_tree_bfs.cs
  codes/csharp/chapter_tree/binary_tree_dfs.cs
  codes/csharp/include/PrintUtil.cs
  codes/csharp/include/TreeNode.cs
  codes/csharp/include/Vertex.cs
Labels: coding, polishing

#476 feat: Add the section of permutations problem.
  codes/cpp/chapter_backtracking/permutations_i.cpp
  codes/cpp/chapter_backtracking/permutations_ii.cpp
  codes/java/chapter_backtracking/permutations_i.java
  codes/java/chapter_backtracking/permutations_ii.java
  codes/python/chapter_array_and_linkedlist/array.py
  codes/python/chapter_backtracking/permutations_i.py
  codes/python/chapter_backtracking/permutations_ii.py
  docs/chapter_backtracking/permutations_problem.assets/permutations_i.png
  docs/chapter_backtracking/permutations_problem.assets/permutations_i_pruning.png
  docs/chapter_backtracking/permutations_problem.assets/permutations_ii.png
  docs/chapter_backtracking/permutations_problem.assets/permutations_ii_pruning.png
  docs/chapter_backtracking/permutations_problem.assets/permutations_ii_pruning_summary.png
  docs/chapter_backtracking/permutations_problem.md
  mkdocs.yml
Labels: coding, writing
