Repository krahets/hello-algo, pull requests merged in 2023-10, with the labels that each got.

#812 Update suggestions
  docs/chapter_preface/suggestions.md
Labels: writing, polishing

#826 fix: typo
  docs/chapter_hashing/hash_collision.md
Labels: bug, writing

#827 Update array.md & hash_map.md
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_hashing/hash_map.md
Labels: bug, writing

#818 refactor: Extend vector.h implementation
  codes/c/utils/vector.h
Labels: coding

#820 Add Binary search recur in C code
  codes/c/chapter_divide_and_conquer/CMakeLists.txt
  codes/c/chapter_divide_and_conquer/binary_search_recur.c
Labels: coding

#816 feat(go): add forLoopRecur func
  codes/go/chapter_computational_complexity/recursion.go
  codes/go/chapter_computational_complexity/recursion_test.go
Labels: coding

#839 fix: Fixed the state transition error in minCostClimbingStairsDP and minCostClimbingStairsDPComp function
  codes/go/chapter_dynamic_programming/min_cost_climbing_stairs_dp.go
Labels: coding, polishing

#829 Add Climbing stairs constraint dp in C code
  codes/c/chapter_dynamic_programming/CMakeLists.txt
  codes/c/chapter_dynamic_programming/climbing_stairs_constraint_dp.c
Labels: coding

#844 fix a typo in time_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, writing

#774 feat: n_queens.c translation
  codes/c/chapter_backtracking/CMakeLists.txt
  codes/c/chapter_backtracking/n_queens.c
Labels: codes

#850 fix a Python variable name in list.md
  docs/chapter_array_and_linkedlist/list.md
Labels: bug, codes

#845 fix get() in hash_map_chaining.c
  codes/c/chapter_hashing/hash_map_chaining.c
Labels: bug, code

#865 refactor: Squash the language code blocks and fix list.md
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_backtracking/permutations_problem.md
  docs/chapter_backtracking/subset_sum_problem.md
  docs/chapter_computational_complexity/iteration_and_recursion.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_divide_and_conquer/binary_search_recur.md
  docs/chapter_divide_and_conquer/build_binary_tree_problem.md
  docs/chapter_divide_and_conquer/hanota_problem.md
  docs/chapter_dynamic_programming/dp_problem_features.md
  docs/chapter_dynamic_programming/dp_solution_pipeline.md
  docs/chapter_dynamic_programming/edit_distance_problem.md
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
  docs/chapter_dynamic_programming/knapsack_problem.md
  docs/chapter_dynamic_programming/unbounded_knapsack_problem.md
  docs/chapter_graph/graph_operations.md
  docs/chapter_graph/graph_traversal.md
  docs/chapter_greedy/fractional_knapsack_problem.md
  docs/chapter_greedy/greedy_algorithm.md
  docs/chapter_greedy/max_capacity_problem.md
  docs/chapter_greedy/max_product_cutting_problem.md
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/build_heap.md
  docs/chapter_heap/heap.md
  docs/chapter_heap/top_k.md
  docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.jpg
  docs/chapter_searching/binary_search.md
  docs/chapter_searching/binary_search_edge.md
  docs/chapter_searching/binary_search_insertion.md
  docs/chapter_searching/replace_linear_by_hashing.md
  docs/chapter_sorting/bubble_sort.md
  docs/chapter_sorting/bucket_sort.md
  docs/chapter_sorting/counting_sort.md
  docs/chapter_sorting/heap_sort.md
  docs/chapter_sorting/insertion_sort.md
  docs/chapter_sorting/merge_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/radix_sort.md
  docs/chapter_sorting/selection_sort.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree_traversal.md
Labels: documents

#867 fix: hash_collision.md squared detection description
  docs/chapter_hashing/hash_collision.md
Labels: bug, documents

#879 feat(csharp): add .net building and testing workflow, solution file
  .github/workflows/dotnet.yml
  codes/csharp/csharp.sln
Labels: enhancement

#882 Add workflow_dispatch to Swift, Python and C# CI Check
  .github/workflows/dotnet.yml
  .github/workflows/python.yml
  .github/workflows/swift.yml
Labels: enhancement

#887 Several bug fixes and improvements.
  codes/c/chapter_computational_complexity/recursion.c
  codes/c/chapter_graph/graph_adjacency_list.c
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
  docs/index.assets/hello_algo_header.png
Labels: bug, embellishment

#889 feat: add top_k.c and refactor top_k.js
  codes/c/chapter_heap/CMakeLists.txt
  codes/c/chapter_heap/my_heap.c
  codes/c/chapter_heap/my_heap_test.c
  codes/c/chapter_heap/top_k.c
  codes/cpp/chapter_heap/top_k.cpp
  codes/csharp/chapter_heap/top_k.cs
  codes/dart/chapter_heap/top_k.dart
  codes/go/chapter_heap/top_k.go
  codes/java/chapter_heap/top_k.java
  codes/javascript/chapter_heap/my_heap.js
  codes/javascript/chapter_heap/top_k.js
  codes/python/chapter_heap/top_k.py
  codes/rust/chapter_heap/top_k.rs
Labels: code

#888 refactor: Re-implement merge sort function.
  codes/c/chapter_sorting/merge_sort.c
  codes/cpp/chapter_sorting/merge_sort.cpp
  codes/csharp/chapter_sorting/merge_sort.cs
  codes/go/chapter_sorting/merge_sort.go
  codes/java/chapter_sorting/merge_sort.java
  codes/javascript/chapter_sorting/merge_sort.js
  codes/python/chapter_sorting/merge_sort.py
  codes/typescript/chapter_sorting/merge_sort.ts
Labels: code, embellishment

#894 refactor: Replace vector with array in C code
  codes/c/chapter_backtracking/preorder_traversal_i_compact.c
  codes/c/chapter_backtracking/preorder_traversal_ii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_compact.c
  codes/c/chapter_backtracking/preorder_traversal_iii_template.c
  codes/c/chapter_backtracking/subset_sum_i.c
  codes/c/chapter_backtracking/subset_sum_i_naive.c
  codes/c/chapter_backtracking/subset_sum_ii.c
  codes/c/chapter_tree/array_binary_tree.c
Labels: code

#885 refactor: Re-implement hanota.c
  codes/c/CMakeLists.txt
  codes/c/chapter_divide_and_conquer/hanota.c
  codes/c/utils/print_util.h
Labels: code

#901 feat: Reimplement the graph code for C
  codes/c/chapter_graph/graph_adjacency_list.c
  codes/c/chapter_graph/graph_adjacency_list_test.c
  codes/c/chapter_graph/graph_adjacency_matrix.c
  codes/c/chapter_graph/graph_bfs.c
  codes/c/chapter_graph/graph_dfs.c
  codes/c/utils/common.h
  codes/c/utils/vertex.h
Labels: code

#902 feat: Add the section of terminologies.
  docs/chapter_appendix/terminologies.md
  mkdocs.yml
Labels: documents

#905 Add missing terminologies
  docs/chapter_appendix/terminology.md
Labels: translation
