Repository krahets/hello-algo, pull requests merged in 2024-04, with the labels that each got.

#1208 translation: Add the initial translation for the tree chapter
  docs/chapter_tree/avl_tree.md
  en/docs/chapter_tree/array_representation_of_tree.assets/array_representation_binary_tree.png
  en/docs/chapter_tree/array_representation_of_tree.assets/array_representation_complete_binary_tree.png
  en/docs/chapter_tree/array_representation_of_tree.assets/array_representation_with_empty.png
  en/docs/chapter_tree/array_representation_of_tree.assets/array_representation_without_empty.png
  en/docs/chapter_tree/array_representation_of_tree.md
  en/docs/chapter_tree/avl_tree.assets/avltree_degradation_from_inserting_node.png
  en/docs/chapter_tree/avl_tree.assets/avltree_degradation_from_removing_node.png
  en/docs/chapter_tree/avl_tree.assets/avltree_left_right_rotate.png
  en/docs/chapter_tree/avl_tree.assets/avltree_left_rotate.png
  en/docs/chapter_tree/avl_tree.assets/avltree_left_rotate_with_grandchild.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_left_rotate.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_rotate_step1.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_rotate_step2.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_rotate_step3.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_rotate_step4.png
  en/docs/chapter_tree/avl_tree.assets/avltree_right_rotate_with_grandchild.png
  en/docs/chapter_tree/avl_tree.assets/avltree_rotation_cases.png
  en/docs/chapter_tree/avl_tree.md
  en/docs/chapter_tree/binary_search_tree.assets/binary_search_tree.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_degradation.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_inorder_traversal.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_insert.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case1.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case2.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case3_step1.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case3_step2.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case3_step3.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_remove_case3_step4.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_search_step1.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_search_step2.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_search_step3.png
  en/docs/chapter_tree/binary_search_tree.assets/bst_search_step4.png
  en/docs/chapter_tree/binary_search_tree.md
  en/docs/chapter_tree/binary_tree.assets/balanced_binary_tree.png
  en/docs/chapter_tree/binary_tree.assets/binary_tree_add_remove.png
  en/docs/chapter_tree/binary_tree.assets/binary_tree_best_worst_cases.png
  en/docs/chapter_tree/binary_tree.assets/binary_tree_definition.png
  en/docs/chapter_tree/binary_tree.assets/binary_tree_terminology.png
  en/docs/chapter_tree/binary_tree.assets/complete_binary_tree.png
  en/docs/chapter_tree/binary_tree.assets/full_binary_tree.png
  en/docs/chapter_tree/binary_tree.assets/perfect_binary_tree.png
  en/docs/chapter_tree/binary_tree.md
  en/docs/chapter_tree/binary_tree_traversal.assets/binary_tree_bfs.png
  en/docs/chapter_tree/binary_tree_traversal.assets/binary_tree_dfs.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step1.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step10.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step11.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step2.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step3.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step4.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step5.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step6.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step7.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step8.png
  en/docs/chapter_tree/binary_tree_traversal.assets/preorder_step9.png
  en/docs/chapter_tree/binary_tree_traversal.md
  en/docs/chapter_tree/index.md
  en/docs/chapter_tree/summary.md
  en/mkdocs.yml
Labels: translation, documents

#1210 Add the initial translation for the Heap chapter
  en/docs/chapter_heap/build_heap.assets/heapify_operations_count.png
  en/docs/chapter_heap/build_heap.md
  en/docs/chapter_heap/heap.assets/heap_pop_step1.png
  en/docs/chapter_heap/heap.assets/heap_pop_step10.png
  en/docs/chapter_heap/heap.assets/heap_pop_step2.png
  en/docs/chapter_heap/heap.assets/heap_pop_step3.png
  en/docs/chapter_heap/heap.assets/heap_pop_step4.png
  en/docs/chapter_heap/heap.assets/heap_pop_step5.png
  en/docs/chapter_heap/heap.assets/heap_pop_step6.png
  en/docs/chapter_heap/heap.assets/heap_pop_step7.png
  en/docs/chapter_heap/heap.assets/heap_pop_step8.png
  en/docs/chapter_heap/heap.assets/heap_pop_step9.png
  en/docs/chapter_heap/heap.assets/heap_push_step1.png
  en/docs/chapter_heap/heap.assets/heap_push_step2.png
  en/docs/chapter_heap/heap.assets/heap_push_step3.png
  en/docs/chapter_heap/heap.assets/heap_push_step4.png
  en/docs/chapter_heap/heap.assets/heap_push_step5.png
  en/docs/chapter_heap/heap.assets/heap_push_step6.png
  en/docs/chapter_heap/heap.assets/heap_push_step7.png
  en/docs/chapter_heap/heap.assets/heap_push_step8.png
  en/docs/chapter_heap/heap.assets/heap_push_step9.png
  en/docs/chapter_heap/heap.assets/min_heap_and_max_heap.png
  en/docs/chapter_heap/heap.assets/representation_of_heap.png
  en/docs/chapter_heap/heap.md
  en/docs/chapter_heap/index.md
  en/docs/chapter_heap/summary.md
  en/docs/chapter_heap/top_k.assets/top_k_heap_step1.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step2.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step3.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step4.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step5.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step6.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step7.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step8.png
  en/docs/chapter_heap/top_k.assets/top_k_heap_step9.png
  en/docs/chapter_heap/top_k.assets/top_k_sorting.png
  en/docs/chapter_heap/top_k.assets/top_k_traversal.png
  en/docs/chapter_heap/top_k.md
  en/mkdocs.yml
Labels: translation, documents

#1211 Add the initial translation for the Graph chapter
  en/docs/chapter_graph/graph.assets/adjacency_list.png
  en/docs/chapter_graph/graph.assets/adjacency_matrix.png
  en/docs/chapter_graph/graph.assets/connected_graph.png
  en/docs/chapter_graph/graph.assets/directed_graph.png
  en/docs/chapter_graph/graph.assets/linkedlist_tree_graph.png
  en/docs/chapter_graph/graph.assets/weighted_graph.png
  en/docs/chapter_graph/graph.md
  en/docs/chapter_graph/graph_operations.assets/adjacency_list_step1_initialization.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_list_step2_add_edge.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_list_step3_remove_edge.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_list_step4_add_vertex.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_list_step5_remove_vertex.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_matrix_step1_initialization.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_matrix_step2_add_edge.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_matrix_step3_remove_edge.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_matrix_step4_add_vertex.png
  en/docs/chapter_graph/graph_operations.assets/adjacency_matrix_step5_remove_vertex.png
  en/docs/chapter_graph/graph_operations.md
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step1.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step10.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step11.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step2.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step3.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step4.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step5.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step6.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step7.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step8.png
  en/docs/chapter_graph/graph_traversal.assets/graph_bfs_step9.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step1.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step10.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step11.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step2.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step3.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step4.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step5.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step6.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step7.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step8.png
  en/docs/chapter_graph/graph_traversal.assets/graph_dfs_step9.png
  en/docs/chapter_graph/graph_traversal.md
  en/docs/chapter_graph/index.md
  en/docs/chapter_graph/summary.md
  en/mkdocs.yml
Labels: translation, documents

#1213 Use underline format for the technical terms
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_array_and_linkedlist/ram_and_cache.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_computational_complexity/iteration_and_recursion.md
  docs/chapter_computational_complexity/performance_evaluation.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/summary.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/character_encoding.md
  docs/chapter_data_structure/number_encoding.md
  docs/chapter_divide_and_conquer/divide_and_conquer.md
  docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
  docs/chapter_graph/graph.md
  docs/chapter_graph/graph_traversal.md
  docs/chapter_greedy/greedy_algorithm.md
  docs/chapter_hashing/hash_collision.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/heap.md
  docs/chapter_introduction/what_is_dsa.md
  docs/chapter_preface/suggestions.md
  docs/chapter_searching/binary_search.md
  docs/chapter_searching/searching_algorithm_revisited.md
  docs/chapter_sorting/bubble_sort.md
  docs/chapter_sorting/bucket_sort.md
  docs/chapter_sorting/counting_sort.md
  docs/chapter_sorting/heap_sort.md
  docs/chapter_sorting/insertion_sort.md
  docs/chapter_sorting/merge_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/radix_sort.md
  docs/chapter_sorting/selection_sort.md
  docs/chapter_sorting/sorting_algorithm.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_search_tree.md
  docs/chapter_tree/binary_tree.md
  docs/chapter_tree/binary_tree_traversal.md
  en/docs/chapter_preface/suggestions.md
Labels: documents, embellishment

#1215 Add the chapter of hello_algo
  docs/assets/covers/chapter_hello_algo.jpg
  docs/chapter_hello_algo/index.md
  docs/chapter_introduction/index.md
  docs/chapter_paperbook/index.md
  docs/chapter_preface/index.md
  docs/index.html
  mkdocs.yml
Labels: documents

#1212 feat: Add Ruby code - chapter "computational complexity"
  codes/ruby/chapter_computational_complexity/iteration.rb
  codes/ruby/chapter_computational_complexity/recursion.rb
  codes/ruby/chapter_computational_complexity/space_complexity.rb
  codes/ruby/chapter_computational_complexity/time_complexity.rb
  codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb
  codes/ruby/utils/print_util.rb
  codes/ruby/utils/tree_node.rb
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: code

#1219 Fix the driver code of quick_sort.cpp
  codes/cpp/chapter_sorting/quick_sort.cpp
Labels: bug, code

#1224 fix: fixed the incorrect use of Chinese designators
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, documents

#1228 Update README for zh-hant version
  README.md
  codes/ruby/chapter_computational_complexity/time_complexity.rb
  codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb
  docs/assets/covers/chapter_appendix.jpg
  docs/assets/covers/chapter_array_and_linkedlist.jpg
  docs/assets/covers/chapter_backtracking.jpg
  docs/assets/covers/chapter_complexity_analysis.jpg
  docs/assets/covers/chapter_data_structure.jpg
  docs/assets/covers/chapter_divide_and_conquer.jpg
  docs/assets/covers/chapter_dynamic_programming.jpg
  docs/assets/covers/chapter_graph.jpg
  docs/assets/covers/chapter_greedy.jpg
  docs/assets/covers/chapter_hashing.jpg
  docs/assets/covers/chapter_heap.jpg
  docs/assets/covers/chapter_introduction.jpg
  docs/assets/covers/chapter_preface.jpg
  docs/assets/covers/chapter_searching.jpg
  docs/assets/covers/chapter_sorting.jpg
  docs/assets/covers/chapter_stack_and_queue.jpg
  docs/assets/covers/chapter_tree.jpg
  docs/chapter_appendix/terminology.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_heap/heap.assets/heap_pop_step10.png
  docs/chapter_heap/heap.assets/heap_push_step9.png
  en/README.md
  en/docs/assets/covers/chapter_appendix.jpg
  en/docs/assets/covers/chapter_array_and_linkedlist.jpg
  en/docs/assets/covers/chapter_backtracking.jpg
  en/docs/assets/covers/chapter_complexity_analysis.jpg
  en/docs/assets/covers/chapter_data_structure.jpg
  en/docs/assets/covers/chapter_divide_and_conquer.jpg
  en/docs/assets/covers/chapter_dynamic_programming.jpg
  en/docs/assets/covers/chapter_graph.jpg
  en/docs/assets/covers/chapter_greedy.jpg
  en/docs/assets/covers/chapter_hashing.jpg
  en/docs/assets/covers/chapter_heap.jpg
  en/docs/assets/covers/chapter_hello_algo.jpg
  en/docs/assets/covers/chapter_introduction.jpg
  en/docs/assets/covers/chapter_preface.jpg
  en/docs/assets/covers/chapter_searching.jpg
  en/docs/assets/covers/chapter_sorting.jpg
  en/docs/assets/covers/chapter_stack_and_queue.jpg
  en/docs/assets/covers/chapter_tree.jpg
  en/docs/index.md
  overrides/main.html
  zh-hant/README.md
  zh-hant/codes/ruby/chapter_computational_complexity/time_complexity.rb
  zh-hant/codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb
  zh-hant/docs/chapter_appendix/terminology.md
  zh-hant/docs/chapter_computational_complexity/space_complexity.md
  zh-hant/docs/chapter_computational_complexity/time_complexity.md
Labels: bug, documents, embellishment

#1198 Simplify kotlin code and improve code readability
  codes/kotlin/chapter_array_and_linkedlist/array.kt
  codes/kotlin/chapter_array_and_linkedlist/linked_list.kt
  codes/kotlin/chapter_array_and_linkedlist/list.kt
  codes/kotlin/chapter_array_and_linkedlist/my_list.kt
  codes/kotlin/chapter_backtracking/n_queens.kt
  codes/kotlin/chapter_backtracking/permutations_i.kt
  codes/kotlin/chapter_backtracking/permutations_ii.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_i_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_ii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_template.kt
  codes/kotlin/chapter_backtracking/subset_sum_i.kt
  codes/kotlin/chapter_backtracking/subset_sum_i_naive.kt
  codes/kotlin/chapter_backtracking/subset_sum_ii.kt
  codes/kotlin/chapter_computational_complexity/space_complexity.kt
  codes/kotlin/chapter_computational_complexity/time_complexity.kt
  codes/kotlin/chapter_computational_complexity/worst_best_time_complexity.kt
Labels: bug, code, embellishment

#1193 Update symbol format in LaTex of number encoding section
  docs/chapter_data_structure/number_encoding.md
  en/docs/chapter_data_structure/number_encoding.md
Labels: bug, documents

#1203 fix memory leak in the C code
  codes/c/chapter_hashing/hash_map_open_addressing.c
  codes/c/chapter_stack_and_queue/linkedlist_deque.c
Labels: bug, code

#1231 fix: Some Ruby code
  codes/ruby/chapter_array_and_linkedlist/array.rb
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, code

#1230 feat: Add Ruby code - chapter "Stack & Queue"
  codes/ruby/chapter_stack_and_queue/array_deque.rb
  codes/ruby/chapter_stack_and_queue/array_queue.rb
  codes/ruby/chapter_stack_and_queue/array_stack.rb
  codes/ruby/chapter_stack_and_queue/deque.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_deque.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_queue.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_stack.rb
  codes/ruby/chapter_stack_and_queue/queue.rb
  codes/ruby/chapter_stack_and_queue/stack.rb
Labels: code

#1233 Improve readability of kotlin code
  codes/kotlin/chapter_divide_and_conquer/build_tree.kt
  codes/kotlin/chapter_divide_and_conquer/hanota.kt
  codes/kotlin/chapter_dynamic_programming/climbing_stairs_backtrack.kt
  codes/kotlin/chapter_dynamic_programming/climbing_stairs_dfs_mem.kt
  codes/kotlin/chapter_dynamic_programming/climbing_stairs_dp.kt
  codes/kotlin/chapter_dynamic_programming/coin_change.kt
  codes/kotlin/chapter_dynamic_programming/edit_distance.kt
  codes/kotlin/chapter_dynamic_programming/knapsack.kt
  codes/kotlin/chapter_dynamic_programming/min_cost_climbing_stairs_dp.kt
  codes/kotlin/chapter_dynamic_programming/min_path_sum.kt
  codes/kotlin/chapter_dynamic_programming/unbounded_knapsack.kt
  codes/kotlin/chapter_graph/graph_adjacency_list.kt
  codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
  codes/kotlin/chapter_graph/graph_bfs.kt
  codes/kotlin/chapter_graph/graph_dfs.kt
Labels: code, embellishment

#1201 translation: chapter_hashing/summary.md
  en/docs/chapter_hashing/summary.md
Labels: translation

#1236 Improve readability of Kotlin code
  codes/kotlin/chapter_greedy/fractional_knapsack.kt
  codes/kotlin/chapter_greedy/max_capacity.kt
  codes/kotlin/chapter_greedy/max_product_cutting.kt
  codes/kotlin/chapter_hashing/array_hash_map.kt
  codes/kotlin/chapter_hashing/built_in_hash.kt
  codes/kotlin/chapter_hashing/hash_map.kt
  codes/kotlin/chapter_hashing/hash_map_chaining.kt
  codes/kotlin/chapter_hashing/hash_map_open_addressing.kt
  codes/kotlin/chapter_hashing/simple_hash.kt
  codes/kotlin/chapter_heap/heap.kt
  codes/kotlin/chapter_heap/my_heap.kt
  codes/kotlin/chapter_searching/hashing_search.kt
Labels: code, embellishment

#1244 fix: zh-hant/README.md `關聯 -> 聯繫`
  zh-hant/README.md
Labels: bug, documents

#1242 Add Ruby test CI
  .github/workflows/ruby.yml
  codes/ruby/test_all.rb
Labels: enhancement, code

#1241 Refine kotlin code
  codes/kotlin/chapter_sorting/bubble_sort.kt
  codes/kotlin/chapter_sorting/bucket_sort.kt
  codes/kotlin/chapter_sorting/counting_sort.kt
  codes/kotlin/chapter_sorting/heap_sort.kt
  codes/kotlin/chapter_sorting/insertion_sort.kt
  codes/kotlin/chapter_sorting/merge_sort.kt
  codes/kotlin/chapter_sorting/radix_sort.kt
  codes/kotlin/chapter_sorting/selection_sort.kt
  codes/kotlin/chapter_stack_and_queue/array_deque.kt
  codes/kotlin/chapter_stack_and_queue/array_queue.kt
  codes/kotlin/chapter_stack_and_queue/array_stack.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_deque.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_queue.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_stack.kt
  codes/kotlin/chapter_tree/array_binary_tree.kt
  codes/kotlin/chapter_tree/avl_tree.kt
  codes/kotlin/chapter_tree/binary_search_tree.kt
  codes/kotlin/chapter_tree/binary_tree_bfs.kt
  codes/kotlin/chapter_tree/binary_tree_dfs.kt
  codes/kotlin/utils/PrintUtil.kt
  codes/kotlin/utils/TreeNode.kt
  codes/kotlin/utils/Vertex.kt
Labels: code, embellishment

#1252 Bug fixes and improvements
  codes/cpp/chapter_tree/avl_tree.cpp
  codes/go/chapter_dynamic_programming/coin_change.go
  codes/go/chapter_dynamic_programming/coin_change_ii.go
  docs/chapter_data_structure/summary.md
  zh-hant/docs/chapter_appendix/terminology.md
  zh-hant/docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.png
  zh-hant/docs/index.html
Labels: bug, code, documents

#1254 feat(Kotlin): Replace `value` with `_val`
  codes/kotlin/chapter_array_and_linkedlist/linked_list.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_i_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_ii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_template.kt
  codes/kotlin/chapter_dynamic_programming/knapsack.kt
  codes/kotlin/chapter_dynamic_programming/unbounded_knapsack.kt
  codes/kotlin/chapter_graph/graph_adjacency_list.kt
  codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
  codes/kotlin/chapter_greedy/fractional_knapsack.kt
  codes/kotlin/chapter_hashing/array_hash_map.kt
  codes/kotlin/chapter_hashing/hash_map.kt
  codes/kotlin/chapter_hashing/hash_map_chaining.kt
  codes/kotlin/chapter_hashing/hash_map_open_addressing.kt
  codes/kotlin/chapter_heap/heap.kt
  codes/kotlin/chapter_heap/my_heap.kt
  codes/kotlin/chapter_searching/hashing_search.kt
  codes/kotlin/chapter_searching/linear_search.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_deque.kt
  codes/kotlin/chapter_tree/array_binary_tree.kt
  codes/kotlin/chapter_tree/avl_tree.kt
  codes/kotlin/chapter_tree/binary_search_tree.kt
  codes/kotlin/chapter_tree/binary_tree_bfs.kt
  codes/kotlin/chapter_tree/binary_tree_dfs.kt
  codes/kotlin/utils/ListNode.kt
  codes/kotlin/utils/PrintUtil.kt
  codes/kotlin/utils/TreeNode.kt
  codes/kotlin/utils/Vertex.kt
Labels: code, embellishment

#1247 feat: add correct comment for RUBY
  docs/chapter_preface/suggestions.md
Labels: code, documents

#1249 fix(Java): Add the brackets to `for` loop
  codes/java/chapter_sorting/radix_sort.java
Labels: bug, code

#1264 fix(Kotlin): Remove empty lines
  codes/kotlin/chapter_backtracking/subset_sum_i.kt
  codes/kotlin/chapter_backtracking/subset_sum_ii.kt
  codes/kotlin/chapter_computational_complexity/recursion.kt
  codes/kotlin/chapter_dynamic_programming/coin_change.kt
  codes/kotlin/chapter_dynamic_programming/knapsack.kt
  codes/kotlin/chapter_greedy/max_product_cutting.kt
  codes/kotlin/chapter_hashing/hash_map_chaining.kt
  codes/kotlin/chapter_heap/my_heap.kt
  codes/kotlin/chapter_sorting/heap_sort.kt
  codes/kotlin/chapter_sorting/insertion_sort.kt
  codes/kotlin/chapter_sorting/merge_sort.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_deque.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_queue.kt
  codes/kotlin/chapter_tree/binary_tree_bfs.kt
  codes/kotlin/utils/ListNode.kt
  codes/kotlin/utils/PrintUtil.kt
Labels: bug, code

#1265 chore: Update Ruby driver code
  codes/ruby/chapter_array_and_linkedlist/array.rb
  codes/ruby/chapter_array_and_linkedlist/linked_list.rb
  codes/ruby/chapter_array_and_linkedlist/list.rb
  codes/ruby/chapter_array_and_linkedlist/my_list.rb
  codes/ruby/chapter_computational_complexity/iteration.rb
  codes/ruby/chapter_computational_complexity/recursion.rb
  codes/ruby/chapter_computational_complexity/space_complexity.rb
  codes/ruby/chapter_computational_complexity/time_complexity.rb
  codes/ruby/chapter_computational_complexity/worst_best_time_complexity.rb
  codes/ruby/chapter_stack_and_queue/array_deque.rb
  codes/ruby/chapter_stack_and_queue/array_queue.rb
  codes/ruby/chapter_stack_and_queue/array_stack.rb
  codes/ruby/chapter_stack_and_queue/deque.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_deque.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_queue.rb
  codes/ruby/chapter_stack_and_queue/linkedlist_stack.rb
  codes/ruby/chapter_stack_and_queue/queue.rb
  codes/ruby/chapter_stack_and_queue/stack.rb
Labels: bug, code

#1269 translation: Add the chapter of hello algo
  en/docs/assets/covers/chapter_introduction.jpg
  en/docs/chapter_hello_algo/index.md
  en/docs/chapter_introduction/index.md
  en/mkdocs.yml
Labels: translation, documents

#1272 fix(C): fix array_hash_map.c and bucket_sort.c
  codes/c/chapter_hashing/array_hash_map.c
  codes/c/chapter_sorting/bucket_sort.c
  zh-hant/codes/c/chapter_hashing/array_hash_map.c
  zh-hant/codes/c/chapter_sorting/bucket_sort.c
Labels: bug, code

#1238 translation: Add the contributing guidelines for Chinese-to-English
  en/CONTRIBUTING.md
  en/README.md
Labels: translation

#1268 Improve the consistency between code and comments in Kotlin
  codes/c/chapter_heap/my_heap.c
  codes/kotlin/chapter_array_and_linkedlist/linked_list.kt
  codes/kotlin/chapter_computational_complexity/recursion.kt
  codes/kotlin/chapter_computational_complexity/time_complexity.kt
  codes/kotlin/chapter_computational_complexity/worst_best_time_complexity.kt
  codes/kotlin/chapter_dynamic_programming/climbing_stairs_dp.kt
  codes/kotlin/chapter_dynamic_programming/knapsack.kt
  codes/kotlin/chapter_graph/graph_adjacency_list.kt
  codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
  codes/kotlin/chapter_hashing/array_hash_map.kt
  codes/kotlin/chapter_hashing/built_in_hash.kt
  codes/kotlin/chapter_hashing/hash_map_chaining.kt
  codes/kotlin/chapter_hashing/simple_hash.kt
  codes/kotlin/chapter_heap/my_heap.kt
  codes/kotlin/chapter_sorting/bubble_sort.kt
  codes/kotlin/chapter_sorting/heap_sort.kt
  codes/kotlin/chapter_sorting/quick_sort.kt
  codes/kotlin/chapter_sorting/selection_sort.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_stack.kt
  codes/kotlin/chapter_tree/array_binary_tree.kt
  codes/kotlin/chapter_tree/binary_tree_bfs.kt
  codes/kotlin/chapter_tree/binary_tree_dfs.kt
  codes/swift/chapter_dynamic_programming/climbing_stairs_backtrack.swift
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_tree/array_representation_of_tree.md
Labels: bug, code, embellishment

#1277 fix(C): fix the array initialization in coin_change.c
  codes/c/chapter_dynamic_programming/coin_change.c
Labels: bug, code

#1274 Prepare 1.1.0 release
  codes/c/chapter_sorting/bucket_sort.c
  codes/c/chapter_sorting/quick_sort.c
  docs/chapter_preface/about_the_book.md
  mkdocs.yml
  overrides/main.html
  zh-hant/codes/c/chapter_dynamic_programming/coin_change.c
  zh-hant/codes/c/chapter_hashing/array_hash_map.c
  zh-hant/codes/c/chapter_heap/my_heap.c
  zh-hant/codes/c/chapter_sorting/bucket_sort.c
  zh-hant/codes/c/chapter_sorting/quick_sort.c
  zh-hant/codes/kotlin/chapter_array_and_linkedlist/linked_list.kt
  zh-hant/codes/kotlin/chapter_computational_complexity/recursion.kt
  zh-hant/codes/kotlin/chapter_computational_complexity/time_complexity.kt
  zh-hant/codes/kotlin/chapter_computational_complexity/worst_best_time_complexity.kt
  zh-hant/codes/kotlin/chapter_dynamic_programming/climbing_stairs_dp.kt
  zh-hant/codes/kotlin/chapter_dynamic_programming/knapsack.kt
  zh-hant/codes/kotlin/chapter_graph/graph_adjacency_list.kt
  zh-hant/codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
  zh-hant/codes/kotlin/chapter_hashing/array_hash_map.kt
  zh-hant/codes/kotlin/chapter_hashing/built_in_hash.kt
  zh-hant/codes/kotlin/chapter_hashing/hash_map_chaining.kt
  zh-hant/codes/kotlin/chapter_hashing/simple_hash.kt
  zh-hant/codes/kotlin/chapter_heap/my_heap.kt
  zh-hant/codes/kotlin/chapter_sorting/bubble_sort.kt
  zh-hant/codes/kotlin/chapter_sorting/heap_sort.kt
  zh-hant/codes/kotlin/chapter_sorting/quick_sort.kt
  zh-hant/codes/kotlin/chapter_sorting/selection_sort.kt
  zh-hant/codes/kotlin/chapter_stack_and_queue/linkedlist_stack.kt
  zh-hant/codes/kotlin/chapter_tree/array_binary_tree.kt
  zh-hant/codes/kotlin/chapter_tree/binary_tree_bfs.kt
  zh-hant/codes/kotlin/chapter_tree/binary_tree_dfs.kt
  zh-hant/codes/ruby/chapter_searching/binary_search.rb
  zh-hant/codes/ruby/chapter_searching/binary_search_edge.rb
  zh-hant/codes/ruby/chapter_searching/binary_search_insertion.rb
  zh-hant/codes/ruby/chapter_searching/hashing_search.rb
  zh-hant/codes/ruby/chapter_searching/linear_search.rb
  zh-hant/codes/ruby/chapter_searching/two_sum.rb
  zh-hant/codes/ruby/chapter_sorting/insertion_sort.rb
  zh-hant/codes/swift/chapter_dynamic_programming/climbing_stairs_backtrack.swift
  zh-hant/docs/chapter_array_and_linkedlist/list.md
  zh-hant/docs/chapter_preface/about_the_book.md
  zh-hant/docs/chapter_tree/array_representation_of_tree.md
  zh-hant/mkdocs.yml
Labels: bug, code, documents, embellishment

#1278 fix(C): Update common.h
  codes/c/utils/common.h
Labels: bug, code

#1266 translation: Update chapter_graph/index.md
  en/docs/chapter_graph/index.md
Labels: translation, documents

#1280 feat(TypeScript): Add the workflow file for CI check
  .github/workflows/typescript.yml
  codes/typescript/.gitignore
  codes/typescript/chapter_graph/graph_adjacency_list.ts
  codes/typescript/chapter_heap/my_heap.ts
  codes/typescript/chapter_tree/array_binary_tree.ts
  codes/typescript/modules/PrintUtil.ts
  codes/typescript/package.json
  codes/typescript/tsconfig.json
Labels: enhancement, code

#1293 feat: Add ruby code blocks - chapter "Tree"
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
Labels: code, documents

#1297 fix(Golang): Fix incorrect indexes in two_sum.go
  codes/go/chapter_searching/two_sum.go
Labels: bug, code

#1286 Translation: Update index.md
  en/docs/chapter_tree/index.md
Labels: translation, documents

#1303 feat: Add ruby code - chapter "Graph"
  codes/ruby/chapter_graph/graph_adjacency_list.rb
  codes/ruby/chapter_graph/graph_adjacency_matrix.rb
  codes/ruby/chapter_graph/graph_bfs.rb
  codes/ruby/chapter_graph/graph_dfs.rb
  codes/ruby/utils/print_util.rb
  codes/ruby/utils/vertex.rb
Labels: code

#1304 Enhance accessibility of MathJax script loading with `cdnjs`
  mkdocs.yml
Labels: enhancement

#1309 fix(Rust): Update my_heap.rs
  codes/rust/chapter_heap/my_heap.rs
Labels: bug, code

#1310 feat: Add glossary and description for "哈希集合"
  codes/cpp/chapter_graph/graph_bfs.cpp
  codes/cpp/chapter_graph/graph_dfs.cpp
  codes/csharp/chapter_graph/graph_bfs.cs
  codes/csharp/chapter_graph/graph_dfs.cs
  codes/dart/chapter_graph/graph_bfs.dart
  codes/dart/chapter_graph/graph_dfs.dart
  codes/go/chapter_graph/graph_bfs.go
  codes/go/chapter_graph/graph_dfs.go
  codes/java/chapter_graph/graph_bfs.java
  codes/java/chapter_graph/graph_dfs.java
  codes/javascript/chapter_graph/graph_bfs.js
  codes/javascript/chapter_graph/graph_dfs.js
  codes/kotlin/chapter_graph/graph_bfs.kt
  codes/kotlin/chapter_graph/graph_dfs.kt
  codes/python/chapter_graph/graph_bfs.py
  codes/python/chapter_graph/graph_dfs.py
  codes/ruby/chapter_graph/graph_bfs.rb
  codes/ruby/chapter_graph/graph_dfs.rb
  codes/rust/chapter_graph/graph_bfs.rs
  codes/rust/chapter_graph/graph_dfs.rs
  codes/swift/chapter_graph/graph_bfs.swift
  codes/swift/chapter_graph/graph_dfs.swift
  codes/typescript/chapter_graph/graph_bfs.ts
  codes/typescript/chapter_graph/graph_dfs.ts
  docs/chapter_appendix/terminology.md
  docs/chapter_backtracking/permutations_problem.md
  docs/chapter_backtracking/summary.md
  docs/chapter_graph/graph_traversal.md
Labels: documents

#1307 fix(typo): Update linked_list.md
  docs/chapter_array_and_linkedlist/linked_list.md
Labels: bug, documents

#1311 feat: update os and swift
  .github/workflows/swift.yml
Labels: bug, code

#1285 feat: add ruby code block - bucket sort
  codes/ruby/chapter_sorting/bucket_sort.rb
Labels: code

#1324 translation: Add the initial translation of chapter "searching"
  en/docs/chapter_hello_algo/index.md
  en/docs/chapter_searching/binary_search.assets/binary_search_example.png
  en/docs/chapter_searching/binary_search.assets/binary_search_ranges.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step1.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step2.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step3.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step4.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step5.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step6.png
  en/docs/chapter_searching/binary_search.assets/binary_search_step7.png
  en/docs/chapter_searching/binary_search.md
  en/docs/chapter_searching/binary_search_edge.assets/binary_search_edge_by_element.png
  en/docs/chapter_searching/binary_search_edge.assets/binary_search_right_edge_by_left_edge.png
  en/docs/chapter_searching/binary_search_edge.md
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_example.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_naive.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step1.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step2.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step3.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step4.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step5.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step6.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step7.png
  en/docs/chapter_searching/binary_search_insertion.assets/binary_search_insertion_step8.png
  en/docs/chapter_searching/binary_search_insertion.md
  en/docs/chapter_searching/index.md
  en/docs/chapter_searching/replace_linear_by_hashing.assets/two_sum_brute_force.png
  en/docs/chapter_searching/replace_linear_by_hashing.assets/two_sum_hashtable_step1.png
  en/docs/chapter_searching/replace_linear_by_hashing.assets/two_sum_hashtable_step2.png
  en/docs/chapter_searching/replace_linear_by_hashing.assets/two_sum_hashtable_step3.png
  en/docs/chapter_searching/replace_linear_by_hashing.md
  en/docs/chapter_searching/searching_algorithm_revisited.assets/searching_algorithms.png
  en/docs/chapter_searching/searching_algorithm_revisited.md
  en/docs/chapter_searching/summary.md
Labels: translation, documents

#1322 translation: Add the initial translation of chapter "divide and conquer"
  en/docs/chapter_divide_and_conquer/binary_search_recur.assets/binary_search_recur.png
  en/docs/chapter_divide_and_conquer/binary_search_recur.md
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/build_tree_division_pointers.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/build_tree_example.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/build_tree_preorder_inorder_division.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_overall.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step1.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step2.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step3.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step4.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step5.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step6.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step7.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step8.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.assets/built_tree_step9.png
  en/docs/chapter_divide_and_conquer/build_binary_tree_problem.md
  en/docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_bubble_sort.png
  en/docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_merge_sort.png
  en/docs/chapter_divide_and_conquer/divide_and_conquer.assets/divide_and_conquer_parallel_computing.png
  en/docs/chapter_divide_and_conquer/divide_and_conquer.md
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_divide_and_conquer.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_example.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f1_step1.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f1_step2.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step1.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step2.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step3.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f2_step4.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step1.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step2.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step3.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_f3_step4.png
  en/docs/chapter_divide_and_conquer/hanota_problem.assets/hanota_recursive_tree.png
  en/docs/chapter_divide_and_conquer/hanota_problem.md
  en/docs/chapter_divide_and_conquer/index.md
  en/docs/chapter_divide_and_conquer/summary.md
Labels: translation, documents

#1323 translation: Add the initial translation of chapter "backtracking"
  en/docs/chapter_backtracking/backtracking_algorithm.assets/backtrack_remove_return_or_not.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_constrained_paths.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_nodes.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step1.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step10.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step11.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step2.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step3.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step4.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step5.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step6.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step7.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step8.png
  en/docs/chapter_backtracking/backtracking_algorithm.assets/preorder_find_paths_step9.png
  en/docs/chapter_backtracking/backtracking_algorithm.md
  en/docs/chapter_backtracking/index.md
  en/docs/chapter_backtracking/n_queens_problem.assets/n_queens_cols_diagonals.png
  en/docs/chapter_backtracking/n_queens_problem.assets/n_queens_constraints.png
  en/docs/chapter_backtracking/n_queens_problem.assets/n_queens_placing.png
  en/docs/chapter_backtracking/n_queens_problem.assets/solution_4_queens.png
  en/docs/chapter_backtracking/n_queens_problem.md
  en/docs/chapter_backtracking/permutations_problem.assets/permutations_i.png
  en/docs/chapter_backtracking/permutations_problem.assets/permutations_i_pruning.png
  en/docs/chapter_backtracking/permutations_problem.assets/permutations_ii.png
  en/docs/chapter_backtracking/permutations_problem.assets/permutations_ii_pruning.png
  en/docs/chapter_backtracking/permutations_problem.assets/permutations_ii_pruning_summary.png
  en/docs/chapter_backtracking/permutations_problem.md
  en/docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i.png
  en/docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i_naive.png
  en/docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_i_pruning.png
  en/docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_ii.png
  en/docs/chapter_backtracking/subset_sum_problem.assets/subset_sum_ii_repeat.png
  en/docs/chapter_backtracking/subset_sum_problem.md
  en/docs/chapter_backtracking/summary.md
Labels: translation, documents

#1325 translation: Add the initial translation of chapter "appendix"
  en/docs/chapter_appendix/contribution.assets/edit_markdown.png
  en/docs/chapter_appendix/contribution.md
  en/docs/chapter_appendix/index.md
  en/docs/chapter_appendix/installation.assets/vscode_extension_installation.png
  en/docs/chapter_appendix/installation.assets/vscode_installation.png
  en/docs/chapter_appendix/installation.md
  en/docs/chapter_appendix/terminology.md
Labels: translation, documents

#1320 translation: Add the initial translation of chapter "greedy"
  en/docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_area_chart.png
  en/docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_example.png
  en/docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_greedy_strategy.png
  en/docs/chapter_greedy/fractional_knapsack_problem.assets/fractional_knapsack_unit_value.png
  en/docs/chapter_greedy/fractional_knapsack_problem.md
  en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_strategy.png
  en/docs/chapter_greedy/greedy_algorithm.assets/coin_change_greedy_vs_dp.png
  en/docs/chapter_greedy/greedy_algorithm.md
  en/docs/chapter_greedy/index.md
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_example.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step1.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step2.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step3.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step4.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step5.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step6.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step7.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step8.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_greedy_step9.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_initial_state.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_long_board.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_moving_short_board.png
  en/docs/chapter_greedy/max_capacity_problem.assets/max_capacity_skipped_states.png
  en/docs/chapter_greedy/max_capacity_problem.md
  en/docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_definition.png
  en/docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_calculation.png
  en/docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer1.png
  en/docs/chapter_greedy/max_product_cutting_problem.assets/max_product_cutting_greedy_infer2.png
  en/docs/chapter_greedy/max_product_cutting_problem.md
  en/docs/chapter_greedy/summary.md
Labels: translation, documents

#1326 Add intial translation of "reference" and fix bugs
  en/docs/chapter_appendix/installation.md
  en/docs/chapter_backtracking/backtracking_algorithm.md
  en/docs/chapter_dynamic_programming/dp_problem_features.md
  en/docs/chapter_dynamic_programming/edit_distance_problem.md
  en/docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
  en/docs/chapter_dynamic_programming/knapsack_problem.md
  en/docs/chapter_dynamic_programming/summary.md
  en/docs/chapter_dynamic_programming/unbounded_knapsack_problem.md
  en/docs/chapter_greedy/fractional_knapsack_problem.md
  en/docs/chapter_greedy/max_product_cutting_problem.md
  en/docs/chapter_reference/index.md
  en/docs/chapter_sorting/counting_sort.md
  en/docs/chapter_sorting/merge_sort.md
  en/mkdocs.yml
Labels: bug, translation, documents
