Repository krahets/hello-algo, pull requests merged in 2024-02, with the labels that each got.

#1045 translation: Update chapter_data_structure/character_encoding.md
  docs-en/chapter_data_structure/character_encoding.md
Labels: translation, documents

#1048 translation: Update chapter_stack_and_queue/summary.md
  docs-en/chapter_stack_and_queue/summary.md
Labels: translation, documents

#1070 feat(Kotlin): Add Kotlin code for the array and linked list chapter
  codes/kotlin/chapter_array_and_linkedlist/array.kt
  codes/kotlin/chapter_array_and_linkedlist/linked_list.kt
  codes/kotlin/chapter_array_and_linkedlist/list.kt
  codes/kotlin/chapter_array_and_linkedlist/my_list.kt
Labels: code

#1042 translation: Updated chapter_array_and_linkedlist/linked_list.md
  docs-en/chapter_array_and_linkedlist/linked_list.md
Labels: translation, documents

#1078 Bug fixes and improvements
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_initial_state.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_state_definition.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.assets/min_path_sum_solution_state_transition.png
  docs/chapter_dynamic_programming/dp_solution_pipeline.md
  docs/chapter_graph/graph_operations.assets/adjacency_list_step1_initialization.png
  docs/chapter_graph/graph_operations.assets/adjacency_list_step2_add_edge.png
  docs/chapter_graph/graph_operations.assets/adjacency_list_step3_remove_edge.png
  docs/chapter_graph/graph_operations.assets/adjacency_list_step4_add_vertex.png
  docs/chapter_graph/graph_operations.assets/adjacency_list_step5_remove_vertex.png
  docs/chapter_graph/graph_operations.assets/adjacency_matrix_step1_initialization.png
  docs/chapter_graph/graph_operations.assets/adjacency_matrix_step2_add_edge.png
  docs/chapter_graph/graph_operations.assets/adjacency_matrix_step3_remove_edge.png
  docs/chapter_graph/graph_operations.assets/adjacency_matrix_step4_add_vertex.png
  docs/chapter_graph/graph_operations.assets/adjacency_matrix_step5_remove_vertex.png
  docs/chapter_graph/graph_operations.md
  docs/chapter_stack_and_queue/deque.assets/array_deque_step1.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_step2_push_last.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_step3_push_first.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_step4_pop_last.png
  docs/chapter_stack_and_queue/deque.assets/array_deque_step5_pop_first.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_step1.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_step2_push_last.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_step3_push_first.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_step4_pop_last.png
  docs/chapter_stack_and_queue/deque.assets/linkedlist_deque_step5_pop_first.png
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.assets/array_queue_step1.png
  docs/chapter_stack_and_queue/queue.assets/array_queue_step2_push.png
  docs/chapter_stack_and_queue/queue.assets/array_queue_step3_pop.png
  docs/chapter_stack_and_queue/queue.assets/linkedlist_queue_step1.png
  docs/chapter_stack_and_queue/queue.assets/linkedlist_queue_step2_push.png
  docs/chapter_stack_and_queue/queue.assets/linkedlist_queue_step3_pop.png
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.assets/array_stack_step1.png
  docs/chapter_stack_and_queue/stack.assets/array_stack_step2_push.png
  docs/chapter_stack_and_queue/stack.assets/array_stack_step3_pop.png
  docs/chapter_stack_and_queue/stack.assets/linkedlist_stack_step1.png
  docs/chapter_stack_and_queue/stack.assets/linkedlist_stack_step2_push.png
  docs/chapter_stack_and_queue/stack.assets/linkedlist_stack_step3_pop.png
  docs/chapter_stack_and_queue/stack.md
  docs/index.assets/hello_algo_hero.jpg
  docs/index.md
  mkdocs-en.yml
  mkdocs.yml
  overrides/assets/images/favicon.png
  overrides/assets/images/logo.png
  overrides/assets/images/logo.svg
  overrides/stylesheets/extra.css
Labels: bug, documents, embellishment

#1088 feat(kotlin): Add kotlin code for backtracking chapter
  codes/kotlin/chapter_backtracking/n_queens/n_queens.kt
  codes/kotlin/chapter_backtracking/permutations_i/permutations_i.kt
  codes/kotlin/chapter_backtracking/permutations_ii/permutations_ii.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_i_compact/preorder_traversal_i_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_ii_compact/preorder_traversal_ii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_compact/preorder_traversal_iii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_template/preorder_traversal_iii_template.kt
  codes/kotlin/chapter_backtracking/subset_sum_i/subset_sum_i.kt
  codes/kotlin/chapter_backtracking/subset_sum_i_naive/subset_sum_i_naive.kt
  codes/kotlin/chapter_backtracking/subset_sum_ii/subset_sum_ii.kt
Labels: code

#1092 Bug fixes and improvements
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_data_structure/number_encoding.assets/1s_2s_complement.png
  docs/chapter_introduction/algorithms_are_everywhere.assets/greedy_change.png
  docs/chapter_preface/suggestions.md
  docs/chapter_sorting/quick_sort.assets/pivot_division_step1.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step2.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step3.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step4.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step5.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step6.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step7.png
  docs/chapter_sorting/quick_sort.assets/pivot_division_step8.png
  docs/chapter_stack_and_queue/stack.assets/array_stack_step2_push.png
Labels: bug, documents

#1089 fix some bugs in c codes
  codes/c/chapter_tree/binary_search_tree.c
  codes/c/utils/common_test.c
Labels: bug, code

#1090 Add Kotlin code for computational complexity
  codes/kotlin/chapter_backtracking/n_queens.kt
  codes/kotlin/chapter_backtracking/permutations_i.kt
  codes/kotlin/chapter_backtracking/permutations_ii.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_i_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_ii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_compact.kt
  codes/kotlin/chapter_backtracking/preorder_traversal_iii_template.kt
  codes/kotlin/chapter_backtracking/subset_sum_i.kt
  codes/kotlin/chapter_backtracking/subset_sum_i_naive.kt
  codes/kotlin/chapter_backtracking/subset_sum_ii.kt
  codes/kotlin/chapter_computational_complexity/iteration.kt
  codes/kotlin/chapter_computational_complexity/recursion.kt
  codes/kotlin/chapter_computational_complexity/space_complexity.kt
  codes/kotlin/chapter_computational_complexity/time_complexity.kt
  codes/kotlin/chapter_computational_complexity/worst_best_time_complexity.kt
Labels: code

#1098 Add kotlin code for the chapter of divide and conquer
  codes/kotlin/chapter_divide_and_conquer/binary_search_recur.kt
  codes/kotlin/chapter_divide_and_conquer/build_tree.kt
  codes/kotlin/chapter_divide_and_conquer/hanota.kt
Labels: code

#1079 translation: Update the figures in the chapter of preface and introduction
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step1.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step2.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step3.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step4.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step5.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/greedy_change.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/playing_cards_sorting.png
  docs-en/chapter_introduction/what_is_dsa.assets/assembling_blocks.jpg
  docs-en/chapter_introduction/what_is_dsa.assets/assembling_blocks.png
  docs-en/chapter_introduction/what_is_dsa.assets/relationship_between_data_structure_and_algorithm.png
  docs-en/chapter_introduction/what_is_dsa.md
  docs-en/chapter_preface/suggestions.assets/code_md_to_repo.png
  docs-en/chapter_preface/suggestions.assets/download_code.png
  docs-en/chapter_preface/suggestions.assets/learning_route.png
  docs-en/chapter_preface/suggestions.assets/pythontutor_example.png
Labels: translation, documents

#1082 translation: Update the figures for the chapter of array and linked list
  docs-en/chapter_array_and_linkedlist/array.assets/array_definition.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_insert_element.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_memory_location_calculation.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_remove_element.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_common_types.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_definition.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_insert_node.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_remove_node.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/computer_storage_devices.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/storage_pyramid.png
Labels: translation, documents
