Repository krahets/hello-algo, pull requests merged in 2024-12, with the labels that each got.

#1578 Update time_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: documents

#1581 Bug fixes and improvements
  .gitignore
  docs/chapter_array_and_linkedlist/summary.md
  docs/chapter_introduction/summary.md
  docs/chapter_introduction/what_is_dsa.md
  en/CONTRIBUTING.md
  en/docs/index.html
  zh-hant/codes/cpp/chapter_tree/array_binary_tree.cpp
  zh-hant/docs/chapter_array_and_linkedlist/summary.md
  zh-hant/docs/chapter_computational_complexity/time_complexity.md
  zh-hant/docs/chapter_introduction/summary.md
  zh-hant/docs/chapter_introduction/what_is_dsa.md
Labels: bug, documents, polish

#1599 fix(hash_collision): typo of zh-Hant translation in "線性探查" section
  zh-hant/docs/chapter_hashing/hash_collision.md
  zh-hant/docs/chapter_hashing/summary.md
Labels: bug, translation, documents
