Repository krahets/hello-algo, pull requests merged in 2024-01, with the labels that each got.

#1005 translation: Update classification_of_data_structure.md
  docs-en/chapter_data_structure/classification_of_data_structure.md
Labels: translation, documents

#1021 Fix some code bugs
  codes/c/chapter_hashing/hash_map_open_addressing.c
  codes/c/chapter_sorting/counting_sort.c
  codes/c/chapter_tree/binary_search_tree.c
Labels: bug, code

#1024 Fix two figures
  docs-en/assets/covers/chapter_introduction.jpg
  docs/chapter_graph/graph_traversal.assets/graph_bfs_step4.png
  docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.jpg
  docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.png
  docs/chapter_preface/about_the_book.md
Labels: bug, documents

#1018 translation: update chapter_data_structure/basic_data_types.md
  docs-en/chapter_data_structure/basic_data_types.md
Labels: translation, documents

#1025 fix(cpp): cmake compile `my_list.cpp` for target list
  codes/cpp/chapter_array_and_linkedlist/CMakeLists.txt
Labels: bug, code

#1012 translation: Update chapter_data_structure/number_encoding.md
  docs-en/chapter_data_structure/number_encoding.md
Labels: translation, documents

#999 translation: chapter_preface/suggestions.md
  docs-en/chapter_preface/suggestions.md
Labels: translation, documents

#1009 translation: Update index.md
  docs-en/chapter_array_and_linkedlist/index.md
Labels: translation, documents

#1028 Fix: recursion bug for JS and TS
  codes/javascript/chapter_computational_complexity/recursion.js
  codes/typescript/chapter_computational_complexity/recursion.ts
Labels: bug, code

#1030 feat: Add pythontutor blocks to the rest of the chapters
  codes/python/chapter_array_and_linkedlist/linked_list.py
  codes/python/chapter_divide_and_conquer/binary_search_recur.py
  codes/python/chapter_dynamic_programming/coin_change_ii.py
  codes/python/chapter_searching/binary_search.py
  codes/pythontutor/chapter_array_and_linkedlist/array.md
  codes/pythontutor/chapter_array_and_linkedlist/linked_list.md
  codes/pythontutor/chapter_backtracking/preorder_traversal_iii_template.md
  codes/pythontutor/chapter_backtracking/subset_sum_i.md
  codes/pythontutor/chapter_backtracking/subset_sum_i_naive.md
  codes/pythontutor/chapter_backtracking/subset_sum_ii.md
  codes/pythontutor/chapter_divide_and_conquer/binary_search_recur.md
  codes/pythontutor/chapter_divide_and_conquer/build_tree.md
  codes/pythontutor/chapter_divide_and_conquer/hanota.md
  codes/pythontutor/chapter_dynamic_programming/climbing_stairs_backtrack.md
  codes/pythontutor/chapter_dynamic_programming/climbing_stairs_constraint_dp.md
  codes/pythontutor/chapter_dynamic_programming/climbing_stairs_dfs.md
  codes/pythontutor/chapter_dynamic_programming/climbing_stairs_dfs_mem.md
  codes/pythontutor/chapter_dynamic_programming/climbing_stairs_dp.md
  codes/pythontutor/chapter_dynamic_programming/coin_change.md
  codes/pythontutor/chapter_dynamic_programming/coin_change_ii.md
  codes/pythontutor/chapter_dynamic_programming/edit_distance.md
  codes/pythontutor/chapter_dynamic_programming/knapsack.md
  codes/pythontutor/chapter_dynamic_programming/min_cost_climbing_stairs_dp.md
  codes/pythontutor/chapter_dynamic_programming/min_path_sum.md
  codes/pythontutor/chapter_dynamic_programming/unbounded_knapsack.md
  codes/pythontutor/chapter_graph/graph_adjacency_list.md
  codes/pythontutor/chapter_graph/graph_adjacency_matrix.md
  codes/pythontutor/chapter_graph/graph_bfs.md
  codes/pythontutor/chapter_graph/graph_dfs.md
  codes/pythontutor/chapter_greedy/coin_change_greedy.md
  codes/pythontutor/chapter_greedy/fractional_knapsack.md
  codes/pythontutor/chapter_greedy/max_capacity.md
  codes/pythontutor/chapter_greedy/max_product_cutting.md
  codes/pythontutor/chapter_heap/my_heap.md
  codes/pythontutor/chapter_heap/top_k.md
  codes/pythontutor/chapter_searching/binary_search.md
  codes/pythontutor/chapter_searching/binary_search_edge.md
  codes/pythontutor/chapter_searching/binary_search_insertion.md
  codes/pythontutor/chapter_searching/two_sum.md
  codes/pythontutor/chapter_sorting/bubble_sort.md
  codes/pythontutor/chapter_sorting/bucket_sort.md
  codes/pythontutor/chapter_sorting/counting_sort.md
  codes/pythontutor/chapter_sorting/heap_sort.md
  codes/pythontutor/chapter_sorting/insertion_sort.md
  codes/pythontutor/chapter_sorting/merge_sort.md
  codes/pythontutor/chapter_sorting/quick_sort.md
  codes/pythontutor/chapter_sorting/radix_sort.md
  codes/pythontutor/chapter_sorting/selection_sort.md
  codes/pythontutor/chapter_tree/array_binary_tree.md
  codes/pythontutor/chapter_tree/binary_search_tree.md
  codes/pythontutor/chapter_tree/binary_tree_bfs.md
  codes/pythontutor/chapter_tree/binary_tree_dfs.md
  docs/chapter_heap/heap.md
  docs/chapter_preface/suggestions.assets/pythontutor_example.png
  docs/chapter_preface/suggestions.md
  docs/chapter_tree/binary_tree.md
Labels: enhancement, code

#1010 translation: Update array.md
  docs-en/chapter_array_and_linkedlist/array.md
Labels: translation, documents

#1031 Update the format of the Q&As
  docs/chapter_array_and_linkedlist/summary.md
  docs/chapter_backtracking/summary.md
  docs/chapter_computational_complexity/summary.md
  docs/chapter_data_structure/summary.md
  docs/chapter_graph/summary.md
  docs/chapter_hashing/summary.md
  docs/chapter_heap/summary.md
  docs/chapter_sorting/summary.md
  docs/chapter_stack_and_queue/summary.md
  docs/chapter_tree/summary.md
Labels: documents, embellishment

#1033 translation: Add the initial translation of the chapter of stack and queue
  codes/javascript/chapter_stack_and_queue/stack.js
  codes/typescript/chapter_stack_and_queue/stack.ts
  docs-en/chapter_array_and_linkedlist/summary.md
  docs-en/chapter_computational_complexity/summary.md
  docs-en/chapter_data_structure/summary.md
  docs-en/chapter_stack_and_queue/deque.assets/array_deque.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_pop_first.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_push_last.png
  docs-en/chapter_stack_and_queue/deque.assets/deque_operations.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_pop_first.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_last.png
  docs-en/chapter_stack_and_queue/deque.md
  docs-en/chapter_stack_and_queue/index.md
  docs-en/chapter_stack_and_queue/queue.assets/array_queue.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_push.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_push.png
  docs-en/chapter_stack_and_queue/queue.assets/queue_operations.png
  docs-en/chapter_stack_and_queue/queue.md
  docs-en/chapter_stack_and_queue/stack.assets/array_stack.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_push.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_push.png
  docs-en/chapter_stack_and_queue/stack.assets/stack_operations.png
  docs-en/chapter_stack_and_queue/stack.md
  docs-en/chapter_stack_and_queue/summary.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/stack.md
Labels: translation, documents

#1036 feat: Adjust the size of pythontutor blocks
  codes/pythontutor/chapter_array_and_linkedlist/list.md
  docs-en/chapter_stack_and_queue/deque.md
  docs-en/chapter_stack_and_queue/queue.md
  docs-en/chapter_stack_and_queue/stack.md
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/heap.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/binary_tree.md
  mkdocs-en.yml
  overrides/stylesheets/extra.css
Labels: enhancement, documents

#1019 feature: add auto-build-and-test workflow for go
  .github/workflows/go.yml
  codes/go/chapter_computational_complexity/space_complexity.go
  codes/go/chapter_computational_complexity/space_complexity_test.go
  codes/python/test_all.py
Labels: enhancement

#1044 Prepare 1.0.0 release
  codes/c/chapter_backtracking/n_queens.c
  codes/cpp/chapter_backtracking/n_queens.cpp
  codes/csharp/chapter_backtracking/n_queens.cs
  codes/dart/chapter_backtracking/n_queens.dart
  codes/go/chapter_backtracking/n_queens.go
  codes/java/chapter_backtracking/n_queens.java
  codes/javascript/chapter_backtracking/n_queens.js
  codes/python/chapter_backtracking/n_queens.py
  codes/rust/chapter_backtracking/n_queens.rs
  codes/swift/chapter_backtracking/n_queens.swift
  codes/typescript/chapter_backtracking/n_queens.ts
  docs-en/chapter_preface/about_the_book.md
  docs/chapter_appendix/terminology.md
  docs/chapter_array_and_linkedlist/summary.md
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_computational_complexity/performance_evaluation.md
  docs/chapter_data_structure/number_encoding.md
  docs/chapter_data_structure/summary.md
  docs/chapter_divide_and_conquer/build_binary_tree_problem.md
  docs/chapter_dynamic_programming/unbounded_knapsack_problem.md
  docs/chapter_graph/graph.md
  docs/chapter_graph/graph_operations.md
  docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.png
  docs/chapter_preface/about_the_book.md
  docs/chapter_preface/suggestions.md
  docs/chapter_searching/binary_search.md
  docs/chapter_sorting/heap_sort.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_stack_and_queue/summary.md
  docs/chapter_tree/avl_tree.md
  docs/index.md
  mkdocs-en.yml
  mkdocs.yml
Labels: documents

#1026 translation: Update chapter_array_and_linkedlist/summary.md
  docs-en/chapter_array_and_linkedlist/summary.md
Labels: translation, documents

#1053 Improve the landing page, mindmap and pull request template
  .github/pull_request_template.md
  docs-en/index.assets/hello_algo_header.png
  docs-en/index.assets/hello_algo_hero.jpg
  docs-en/index.md
  docs/chapter_preface/about_the_book.assets/hello_algo_mindmap.png
  docs/index.assets/hello_algo_hero.jpg
  docs/index.md
  overrides/stylesheets/extra.css
Labels: documents, embellishment

#1052 fix(csharp): while loop II comment
  codes/csharp/chapter_computational_complexity/iteration.cs
Labels: bug, code

#1059 feat: Redesign the landing page
  docs/assets/hero/astronaut.png
  docs/assets/hero/chapter_array_and_linkedlist.png
  docs/assets/hero/chapter_backtracking.png
  docs/assets/hero/chapter_computational_complexity.png
  docs/assets/hero/chapter_divide_and_conquer.png
  docs/assets/hero/chapter_dynamic_programming.png
  docs/assets/hero/chapter_graph.png
  docs/assets/hero/chapter_greedy.png
  docs/assets/hero/chapter_hashing.png
  docs/assets/hero/chapter_heap.png
  docs/assets/hero/chapter_searching.png
  docs/assets/hero/chapter_sorting.png
  docs/assets/hero/chapter_stack_and_queue.png
  docs/assets/hero/chapter_tree.png
  docs/assets/hero/ground.png
  docs/assets/hero/links.png
  docs/assets/hero/pdf_ipad.png
  docs/assets/hero/universe_bg.png
  docs/assets/hero/web_iphone.png
  docs/assets/hero/web_mac.png
  docs/index.assets/hello_algo_header.png
  docs/index.md
  overrides/assets/images/logo.png
  overrides/stylesheets/extra.css
Labels: enhancement

#1060 The 4th revision
  docs/chapter_data_structure/character_encoding.md
  docs/chapter_data_structure/classification_of_data_structure.md
  docs/chapter_sorting/quick_sort.md
Labels: bug, documents, embellishment

#1055 fix(linkedlist_queue.c): Remove redundant conditional judgments.
  codes/c/chapter_stack_and_queue/linkedlist_queue.c
Labels: bug, code

#1057 Update space_complexity.md
  docs/chapter_computational_complexity/space_complexity.md
Labels: bug, documents

#1063 Some bug fixes and improvements
  docs-en/index.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_sorting/insertion_sort.md
  docs/index.md
  overrides/stylesheets/extra.css
Labels: bug, code, documents, embellishment

#1062 fix: Update linkedlist_deque.cpp
  codes/cpp/chapter_stack_and_queue/linkedlist_deque.cpp
Labels: bug, code

#1032 translation: Update chapter_array_and_linkedlist/list.md
  docs-en/chapter_array_and_linkedlist/list.md
Labels: translation, documents

#1035 translation: Update chapter_stack_and_queue/index.md
  docs-en/chapter_stack_and_queue/index.md
Labels: translation, documents

#1066 translation: Add the initial translation of the hashing chapter
  docs-en/chapter_hashing/hash_algorithm.assets/hash_collision_best_worst_condition.png
  docs-en/chapter_hashing/hash_algorithm.md
  docs-en/chapter_hashing/hash_collision.assets/hash_table_chaining.png
  docs-en/chapter_hashing/hash_collision.assets/hash_table_linear_probing.png
  docs-en/chapter_hashing/hash_collision.assets/hash_table_open_addressing_deletion.png
  docs-en/chapter_hashing/hash_collision.md
  docs-en/chapter_hashing/hash_map.assets/hash_collision.png
  docs-en/chapter_hashing/hash_map.assets/hash_function.png
  docs-en/chapter_hashing/hash_map.assets/hash_table_lookup.png
  docs-en/chapter_hashing/hash_map.assets/hash_table_reshash.png
  docs-en/chapter_hashing/hash_map.md
  docs-en/chapter_hashing/index.md
  docs-en/chapter_hashing/summary.md
  docs-en/chapter_stack_and_queue/deque.md
  docs-en/chapter_stack_and_queue/queue.md
  docs-en/chapter_stack_and_queue/stack.md
  docs/chapter_hashing/hash_algorithm.md
  mkdocs-en.yml
Labels: translation, documents

#1038 translation:Update chapter_stack_and_queue/stack.md
  docs-en/chapter_stack_and_queue/stack.md
Labels: translation, documents

#1043 Updated terminology.md
  docs/chapter_appendix/terminology.md
Labels: documents

#1067 Update the landing page, preface and reference
  docs/chapter_introduction/index.md
  docs/chapter_preface/index.md
  docs/chapter_reference/index.md
  docs/index.md
  overrides/stylesheets/extra.css
Labels: documents
