Repository krahets/hello-algo, pull requests merged in 2024-07, with the labels that each got.

#1406 fix: correct comment translation in binary_tree.md
  en/docs/chapter_tree/binary_tree.md
Labels: bug, code

#1411 Rust: remove unnecessary type conversions
  codes/rust/chapter_computational_complexity/time_complexity.rs
Labels: bug, code

#1453 Fix a typo
  en/docs/chapter_introduction/algorithms_are_everywhere.md
Labels: bug, documents

#1448 fix: right-left and left-right inversion for the English version of AVL Tree
  en/docs/chapter_tree/avl_tree.md
Labels: bug, documents

#1472 Bug fixes and improvements
  docs/chapter_backtracking/n_queens_problem.md
  docs/chapter_data_structure/classification_of_data_structure.md
  docs/chapter_preface/about_the_book.md
  docs/chapter_sorting/bucket_sort.md
  docs/chapter_sorting/quick_sort.md
  docs/chapter_sorting/sorting_algorithm.md
  docs/chapter_sorting/summary.assets/sorting_algorithms_comparison.png
  docs/chapter_sorting/summary.md
  en/CONTRIBUTING.md
  en/docs/chapter_backtracking/n_queens_problem.md
  en/docs/chapter_introduction/algorithms_are_everywhere.md
  en/docs/chapter_preface/about_the_book.md
  en/docs/chapter_sorting/bucket_sort.md
  en/docs/chapter_sorting/quick_sort.md
  en/docs/chapter_sorting/sorting_algorithm.md
  en/docs/chapter_sorting/summary.assets/sorting_algorithms_comparison.png
  en/docs/chapter_sorting/summary.md
  mkdocs.yml
  zh-hant/codes/go/chapter_stack_and_queue/array_deque.go
  zh-hant/codes/go/chapter_stack_and_queue/array_queue.go
  zh-hant/codes/go/chapter_stack_and_queue/queue_test.go
  zh-hant/codes/rust/chapter_backtracking/permutations_i.rs
  zh-hant/codes/rust/chapter_backtracking/permutations_ii.rs
  zh-hant/codes/rust/chapter_computational_complexity/time_complexity.rs
  zh-hant/docs/chapter_backtracking/n_queens_problem.md
  zh-hant/docs/chapter_computational_complexity/time_complexity.md
  zh-hant/docs/chapter_data_structure/classification_of_data_structure.md
  zh-hant/docs/chapter_preface/about_the_book.md
  zh-hant/docs/chapter_sorting/bucket_sort.md
  zh-hant/docs/chapter_sorting/quick_sort.md
  zh-hant/docs/chapter_sorting/sorting_algorithm.md
  zh-hant/docs/chapter_sorting/summary.assets/sorting_algorithms_comparison.png
  zh-hant/docs/chapter_sorting/summary.md
  zh-hant/docs/index.html
Labels: bug, code, documents, embellishment
