Repository krahets/hello-algo, pull requests merged in 2024-06, with the labels that each got.

#1386 Make rust more idomatic
  codes/rust/chapter_backtracking/permutations_i.rs
  codes/rust/chapter_backtracking/permutations_ii.rs
Labels: code, embellishment

#1374 translation: refine the translation of data_structure/summary
  en/docs/chapter_data_structure/summary.md
Labels: translation, documents

#1358 translation: optimize the translation of hash_map.md
  en/docs/chapter_hashing/hash_map.md
Labels: translation, documents

#1405 fix invalid code comment
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, code
