Repository krahets/hello-algo, pull requests merged in 2024-03, with the labels that each got.

#1102 Add kotlin code for the chapter of graph
  codes/kotlin/chapter_graph/graph_adjacency_list.kt
  codes/kotlin/chapter_graph/graph_adjacency_matrix.kt
  codes/kotlin/chapter_graph/graph_bfs.kt
  codes/kotlin/chapter_graph/graph_dfs.kt
Labels: code

#1100 translation: Update the mindmap
  docs-en/chapter_preface/about_the_book.assets/hello_algo_mindmap.jpg
  docs-en/chapter_preface/about_the_book.assets/hello_algo_mindmap.png
  docs-en/chapter_preface/about_the_book.md
Labels: translation, documents

#1103 Add kotlin codes for the chapter of greedy
  codes/kotlin/chapter_greedy/coin_change_greedy.kt
  codes/kotlin/chapter_greedy/fractional_knapsack.kt
  codes/kotlin/chapter_greedy/max_capacity.kt
  codes/kotlin/chapter_greedy/max_product_cutting.kt
Labels: code

#1105 Reduce the file size of the landing page
  docs/chapter_preface/suggestions.md
  docs/index.html
  docs/index.md
  mkdocs.yml
  overrides/main.html
  overrides/stylesheets/extra.css
Labels: documents, embellishment

#1084 translation: Update the figures for the chapter of stack and queue
  docs-en/chapter_stack_and_queue/deque.assets/array_deque.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_pop_first.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_push_last.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_step1.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_step2_push_last.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_step3_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_step4_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/array_deque_step5_pop_first.png
  docs-en/chapter_stack_and_queue/deque.assets/deque_operations.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_pop_first.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_push_last.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_step1.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_step2_push_last.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_step3_push_first.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_step4_pop_last.png
  docs-en/chapter_stack_and_queue/deque.assets/linkedlist_deque_step5_pop_first.png
  docs-en/chapter_stack_and_queue/deque.md
  docs-en/chapter_stack_and_queue/queue.assets/array_queue.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_push.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_step1.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_step2_push.png
  docs-en/chapter_stack_and_queue/queue.assets/array_queue_step3_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_push.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_step1.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_step2_push.png
  docs-en/chapter_stack_and_queue/queue.assets/linkedlist_queue_step3_pop.png
  docs-en/chapter_stack_and_queue/queue.assets/queue_operations.png
  docs-en/chapter_stack_and_queue/queue.md
  docs-en/chapter_stack_and_queue/stack.assets/array_stack.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_push.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_step1.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_step2_push.png
  docs-en/chapter_stack_and_queue/stack.assets/array_stack_step3_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_push.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_step1.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_step2_push.png
  docs-en/chapter_stack_and_queue/stack.assets/linkedlist_stack_step3_pop.png
  docs-en/chapter_stack_and_queue/stack.assets/stack_operations.png
  docs-en/chapter_stack_and_queue/stack.md
Labels: translation, documents

#1083 translation: Update the figures for the chapter of data sturcture
  docs-en/chapter_data_structure/character_encoding.assets/ascii_table.png
  docs-en/chapter_data_structure/character_encoding.assets/unicode_hello_algo.png
  docs-en/chapter_data_structure/character_encoding.assets/utf-8_hello_algo.png
  docs-en/chapter_data_structure/classification_of_data_structure.assets/classification_logic_structure.png
  docs-en/chapter_data_structure/classification_of_data_structure.assets/classification_phisical_structure.png
  docs-en/chapter_data_structure/classification_of_data_structure.assets/computer_memory_location.png
  docs-en/chapter_data_structure/number_encoding.assets/1s_2s_complement.png
  docs-en/chapter_data_structure/number_encoding.assets/ieee_754_float.png
Labels: translation, documents

#1080 translation: Update the figures in the chapter of complexity analysis
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/iteration.png
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/nested_iteration.png
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/recursion_sum.png
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/recursion_sum_depth.png
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/recursion_tree.png
  docs-en/chapter_computational_complexity/iteration_and_recursion.assets/tail_recursion_sum.png
  docs-en/chapter_computational_complexity/space_complexity.assets/space_complexity_common_types.png
  docs-en/chapter_computational_complexity/space_complexity.assets/space_complexity_exponential.png
  docs-en/chapter_computational_complexity/space_complexity.assets/space_complexity_recursive_linear.png
  docs-en/chapter_computational_complexity/space_complexity.assets/space_complexity_recursive_quadratic.png
  docs-en/chapter_computational_complexity/space_complexity.assets/space_types.png
  docs-en/chapter_computational_complexity/time_complexity.assets/asymptotic_upper_bound.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_common_types.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_constant_linear_quadratic.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_exponential.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_factorial.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_logarithmic.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_logarithmic_linear.png
  docs-en/chapter_computational_complexity/time_complexity.assets/time_complexity_simple_example.png
Labels: translation, documents

#1114 Add the section of introduction to the paper book
  docs-en/chapter_array_and_linkedlist/array.assets/array_definition.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_insert_element.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_memory_location_calculation.png
  docs-en/chapter_array_and_linkedlist/array.assets/array_remove_element.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_common_types.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_definition.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_insert_node.png
  docs-en/chapter_array_and_linkedlist/linked_list.assets/linkedlist_remove_node.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/computer_storage_devices.png
  docs-en/chapter_array_and_linkedlist/ram_and_cache.assets/storage_pyramid.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step1.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step2.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step3.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step4.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/binary_search_dictionary_step5.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/greedy_change.png
  docs-en/chapter_introduction/algorithms_are_everywhere.assets/playing_cards_sorting.png
  docs-en/chapter_introduction/what_is_dsa.assets/relationship_between_data_structure_and_algorithm.png
  docs-en/chapter_preface/suggestions.assets/code_md_to_repo.png
  docs-en/chapter_preface/suggestions.assets/learning_route.png
  docs/chapter_paperbook/index.assets/book_jd_link.jpg
  docs/chapter_paperbook/index.assets/paper_book_avl_tree.jpg
  docs/chapter_paperbook/index.assets/paper_book_chapter_heap.jpg
  docs/chapter_paperbook/index.assets/paper_book_overview.jpg
  docs/chapter_paperbook/index.md
  docs/chapter_reference/index.md
  docs/index.html
  mkdocs.yml
  overrides/main.html
  overrides/stylesheets/extra.css
Labels: documents

#1068 translation: Update chapter_stack_and_queue/deque.md
  docs-en/chapter_stack_and_queue/deque.md
Labels: translation, documents

#1134 Fix the median_three mehod for quick sort
  codes/c/chapter_sorting/quick_sort.c
  codes/cpp/chapter_sorting/quick_sort.cpp
  codes/csharp/chapter_sorting/quick_sort.cs
  codes/dart/chapter_sorting/quick_sort.dart
  codes/go/chapter_sorting/quick_sort.go
  codes/java/chapter_sorting/quick_sort.java
  codes/javascript/chapter_sorting/quick_sort.js
  codes/python/chapter_sorting/quick_sort.py
  codes/rust/chapter_sorting/quick_sort.rs
  codes/swift/chapter_sorting/quick_sort.swift
  codes/typescript/chapter_sorting/quick_sort.ts
  codes/zig/chapter_sorting/quick_sort.zig
Labels: bug, code

#1106 Optimize the representation of the AVL tree
  docs/chapter_tree/avl_tree.md
Labels: bug, documents

#1144 Fix rust compile warning and an obvious print error in array.rs
  codes/rust/chapter_array_and_linkedlist/array.rs
  codes/rust/chapter_array_and_linkedlist/linked_list.rs
  codes/rust/chapter_sorting/quick_sort.rs
  codes/rust/include/list_node.rs
Labels: bug, code

#1152 Bug fixes and improvements
  codes/csharp/chapter_computational_complexity/time_complexity.cs
  codes/csharp/chapter_sorting/bubble_sort.cs
  codes/go/chapter_hashing/hash_collision_test.go
  codes/go/chapter_hashing/hash_map_open_addressing.go
  codes/rust/chapter_sorting/bubble_sort.rs
  codes/swift/chapter_computational_complexity/time_complexity.swift
  codes/swift/chapter_sorting/bubble_sort.swift
  codes/zig/chapter_computational_complexity/time_complexity.zig
  codes/zig/chapter_sorting/bubble_sort.zig
  docs/chapter_array_and_linkedlist/summary.md
  docs/chapter_paperbook/index.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  mkdocs.yml
  overrides/main.html
Labels: bug, code, documents, embellishment

#1039 translation: Update chapter_stack_and_queue/queue.md
  docs-en/chapter_stack_and_queue/queue.md
Labels: translation, documents

#1155 fix: Update code comment of `quadratic` in time_complexity
  codes/c/chapter_computational_complexity/time_complexity.c
  codes/cpp/chapter_computational_complexity/time_complexity.cpp
  codes/csharp/chapter_computational_complexity/time_complexity.cs
  codes/dart/chapter_computational_complexity/time_complexity.dart
  codes/go/chapter_computational_complexity/time_complexity.go
  codes/java/chapter_computational_complexity/time_complexity.java
  codes/javascript/chapter_computational_complexity/time_complexity.js
  codes/kotlin/chapter_computational_complexity/time_complexity.kt
  codes/python/chapter_computational_complexity/time_complexity.py
  codes/pythontutor/chapter_computational_complexity/time_complexity.md
  codes/rust/chapter_computational_complexity/time_complexity.rs
  codes/swift/chapter_computational_complexity/time_complexity.swift
  codes/typescript/chapter_computational_complexity/time_complexity.ts
  codes/zig/chapter_computational_complexity/time_complexity.zig
Labels: bug, code

#1150 Review Swift codes
  .github/workflows/swift.yml
  codes/swift/Package.swift
  codes/swift/chapter_array_and_linkedlist/array.swift
  codes/swift/chapter_array_and_linkedlist/linked_list.swift
  codes/swift/chapter_array_and_linkedlist/my_list.swift
  codes/swift/chapter_backtracking/subset_sum_i.swift
  codes/swift/chapter_backtracking/subset_sum_i_naive.swift
  codes/swift/chapter_backtracking/subset_sum_ii.swift
  codes/swift/chapter_computational_complexity/recursion.swift
  codes/swift/chapter_computational_complexity/time_complexity.swift
  codes/swift/chapter_divide_and_conquer/binary_search_recur.swift
  codes/swift/chapter_divide_and_conquer/build_tree.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_constraint_dp.swift
  codes/swift/chapter_dynamic_programming/climbing_stairs_dp.swift
  codes/swift/chapter_dynamic_programming/coin_change.swift
  codes/swift/chapter_dynamic_programming/coin_change_ii.swift
  codes/swift/chapter_dynamic_programming/edit_distance.swift
  codes/swift/chapter_dynamic_programming/knapsack.swift
  codes/swift/chapter_dynamic_programming/min_cost_climbing_stairs_dp.swift
  codes/swift/chapter_dynamic_programming/min_path_sum.swift
  codes/swift/chapter_dynamic_programming/unbounded_knapsack.swift
  codes/swift/chapter_graph/graph_adjacency_list.swift
  codes/swift/chapter_greedy/fractional_knapsack.swift
  codes/swift/chapter_greedy/max_capacity.swift
  codes/swift/chapter_hashing/array_hash_map.swift
  codes/swift/chapter_hashing/hash_map_chaining.swift
  codes/swift/chapter_hashing/hash_map_open_addressing.swift
  codes/swift/chapter_heap/heap.swift
  codes/swift/chapter_heap/my_heap.swift
  codes/swift/chapter_heap/top_k.swift
  codes/swift/chapter_searching/binary_search.swift
  codes/swift/chapter_searching/binary_search_edge.swift
  codes/swift/chapter_searching/binary_search_insertion.swift
  codes/swift/chapter_sorting/bubble_sort.swift
  codes/swift/chapter_sorting/bucket_sort.swift
  codes/swift/chapter_sorting/counting_sort.swift
  codes/swift/chapter_sorting/heap_sort.swift
  codes/swift/chapter_sorting/insertion_sort.swift
  codes/swift/chapter_sorting/merge_sort.swift
  codes/swift/chapter_sorting/quick_sort.swift
  codes/swift/chapter_sorting/radix_sort.swift
  codes/swift/chapter_stack_and_queue/array_deque.swift
  codes/swift/chapter_stack_and_queue/array_queue.swift
  codes/swift/chapter_stack_and_queue/linkedlist_deque.swift
  codes/swift/chapter_stack_and_queue/linkedlist_queue.swift
  codes/swift/chapter_stack_and_queue/linkedlist_stack.swift
  codes/swift/chapter_tree/array_binary_tree.swift
  codes/swift/chapter_tree/avl_tree.swift
  codes/swift/chapter_tree/binary_search_tree.swift
  codes/swift/utils/Vertex.swift
  docs-en/chapter_computational_complexity/time_complexity.md
  docs-en/chapter_data_structure/basic_data_types.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_heap/heap.md
Labels: code, embellishment

#1074 translation: Update chapter_computational_complexity/iteration_and_recursion.md
  docs-en/chapter_computational_complexity/iteration_and_recursion.md
Labels: translation, documents

#1164 fix: Use int instead of float for the example code of log time complexity
  codes/c/chapter_computational_complexity/time_complexity.c
  codes/cpp/chapter_computational_complexity/time_complexity.cpp
  codes/csharp/chapter_computational_complexity/time_complexity.cs
  codes/dart/chapter_computational_complexity/time_complexity.dart
  codes/go/chapter_computational_complexity/time_complexity.go
  codes/go/chapter_computational_complexity/time_complexity_test.go
  codes/java/chapter_computational_complexity/time_complexity.java
  codes/kotlin/chapter_computational_complexity/time_complexity.kt
  codes/python/chapter_computational_complexity/time_complexity.py
  codes/rust/chapter_computational_complexity/time_complexity.rs
  codes/swift/chapter_computational_complexity/time_complexity.swift
  codes/zig/chapter_computational_complexity/time_complexity.zig
Labels: bug, code

#1162 Add kotlin code for the chapter of stack and queue
  codes/kotlin/chapter_array_and_linkedlist/array.kt
  codes/kotlin/chapter_stack_and_queue/array_deque.kt
  codes/kotlin/chapter_stack_and_queue/array_queue.kt
  codes/kotlin/chapter_stack_and_queue/array_stack.kt
  codes/kotlin/chapter_stack_and_queue/deque.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_deque.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_queue.kt
  codes/kotlin/chapter_stack_and_queue/linkedlist_stack.kt
  codes/kotlin/chapter_stack_and_queue/queue.kt
  codes/kotlin/chapter_stack_and_queue/stack.kt
Labels: code

#1107 Fix toc for the webpage of the chapter of computational complexity
  docs-en/chapter_computational_complexity/space_complexity.md
  docs-en/chapter_computational_complexity/time_complexity.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
Labels: bug, documents

#1169 Add return value for recur function of Python in space complexity
  docs-en/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/space_complexity.md
Labels: bug, code

#1170 Add the kotlin blocks to the documents
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/heap.md
  docs/chapter_preface/suggestions.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
Labels: code, documents

#1172 Add kotlin code for the chapter of tree
  codes/kotlin/chapter_tree/array_binary_tree.kt
  codes/kotlin/chapter_tree/avl_tree.kt
  codes/kotlin/chapter_tree/binary_search_tree.kt
  codes/kotlin/chapter_tree/binary_tree.kt
  codes/kotlin/chapter_tree/binary_tree_bfs.kt
  codes/kotlin/chapter_tree/binary_tree_dfs.kt
Labels: code

#1175 Add kotlin code for the utils file
  codes/kotlin/utils/ListNode.kt
  codes/kotlin/utils/PrintUtil.kt
  codes/kotlin/utils/TreeNode.kt
  codes/kotlin/utils/Vertex.kt
Labels: code

#1190 Add kotlin code block for the chapter of data structure
  docs/chapter_data_structure/basic_data_types.md
Labels: code, documents

#1196 Add kotlin code block for chapter_heap
  docs/chapter_heap/heap.md
Labels: code, documents

#1158 feat: Add ruby code - chapter "array & linked list"
  codes/ruby/chapter_array_and_linkedlist/array.rb
  codes/ruby/chapter_array_and_linkedlist/linked_list.rb
  codes/ruby/chapter_array_and_linkedlist/list.rb
  codes/ruby/chapter_array_and_linkedlist/my_list.rb
  codes/ruby/utils/list_node.rb
  codes/ruby/utils/print_util.rb
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  en/docs/chapter_array_and_linkedlist/array.md
  en/docs/chapter_array_and_linkedlist/linked_list.md
  en/docs/chapter_array_and_linkedlist/list.md
Labels: code

#1197 Add kotlin code for chapter_stack_and_queue and chapter_tree
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
Labels: code, documents

#1199 Fix bugs and harmonize the code comments
  codes/c/chapter_sorting/bucket_sort.c
  codes/c/utils/common_test.c
  codes/c/utils/list_node.h
  codes/c/utils/print_util.h
  codes/cpp/utils/list_node.hpp
  codes/cpp/utils/print_utils.hpp
  codes/csharp/utils/ListNode.cs
  codes/csharp/utils/PrintUtil.cs
  codes/dart/utils/list_node.dart
  codes/dart/utils/print_util.dart
  codes/go/chapter_stack_and_queue/array_deque.go
  codes/go/pkg/list_node.go
  codes/go/pkg/list_node_test.go
  codes/go/pkg/print_utils.go
  codes/go/pkg/tree_node.go
  codes/go/pkg/vertex.go
  codes/java/utils/ListNode.java
  codes/java/utils/PrintUtil.java
  codes/javascript/modules/ListNode.js
  codes/javascript/modules/PrintUtil.js
  codes/javascript/modules/TreeNode.js
  codes/kotlin/utils/ListNode.kt
  codes/python/modules/list_node.py
  codes/ruby/utils/list_node.rb
  codes/rust/include/list_node.rs
  codes/rust/include/print_util.rs
  codes/typescript/modules/ListNode.ts
  codes/typescript/modules/PrintUtil.ts
  codes/typescript/modules/TreeNode.ts
  codes/zig/include/ListNode.zig
  codes/zig/include/PrintUtil.zig
  codes/zig/include/TreeNode.zig
  docs/chapter_appendix/terminology.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_stack_and_queue/deque.md
Labels: bug, code, documents

#1200 Add Ruby code blocks to the documents
  docs/chapter_array_and_linkedlist/array.md
  docs/chapter_array_and_linkedlist/linked_list.md
  docs/chapter_array_and_linkedlist/list.md
  docs/chapter_backtracking/backtracking_algorithm.md
  docs/chapter_computational_complexity/space_complexity.md
  docs/chapter_computational_complexity/time_complexity.md
  docs/chapter_data_structure/basic_data_types.md
  docs/chapter_hashing/hash_algorithm.md
  docs/chapter_hashing/hash_map.md
  docs/chapter_heap/heap.md
  docs/chapter_preface/suggestions.md
  docs/chapter_stack_and_queue/deque.md
  docs/chapter_stack_and_queue/queue.md
  docs/chapter_stack_and_queue/stack.md
  docs/chapter_tree/array_representation_of_tree.md
  docs/chapter_tree/avl_tree.md
  docs/chapter_tree/binary_tree.md
  en/docs/chapter_array_and_linkedlist/array.md
  en/docs/chapter_array_and_linkedlist/linked_list.md
  en/docs/chapter_array_and_linkedlist/list.md
  overrides/stylesheets/extra.css
Labels: code, documents
