Repository krahets/hello-algo, pull requests merged in 2025-05, with the labels that each got.

#1750 Fix typo in Traditional Chinese translation of binary search
  zh-hant/docs/chapter_searching/binary_search.md
Labels: bug, translation, documents

#1751 Translation: Update intro_to_dynamic_programming.md
  en/docs/chapter_dynamic_programming/intro_to_dynamic_programming.md
Labels: translation, documents

#1737 Update Zig example code
  docs/chapter_data_structure/basic_data_types.md
Labels: code

#1748 optimized the js api use of counting_sort chapter for Math.max()
  codes/javascript/chapter_sorting/counting_sort.js
  codes/javascript/chapter_sorting/radix_sort.js
  codes/typescript/chapter_sorting/counting_sort.ts
  codes/typescript/chapter_sorting/radix_sort.ts
Labels: code, polish

#1412 fix(graph): enhance the judgment of corner case for removeEdge functions
  codes/javascript/chapter_graph/graph_adjacency_list.js
  codes/typescript/chapter_graph/graph_adjacency_list.ts
  zh-hant/codes/javascript/chapter_graph/graph_adjacency_list.js
  zh-hant/codes/typescript/chapter_graph/graph_adjacency_list.ts
Labels: bug, code
