Repository krahets/hello-algo, pull requests merged in 2025-01, with the labels that each got.

#1602 Bug fixes and improvements
  docs/chapter_preface/about_the_book.md
  en/docs/chapter_preface/about_the_book.md
  mkdocs.yml
  overrides/main.html
  overrides/stylesheets/extra.css
  zh-hant/docs/chapter_preface/about_the_book.md
Labels: bug, documents, polish

#1609 fix rust linked list
  codes/rust/chapter_array_and_linkedlist/array.rs
  codes/rust/chapter_array_and_linkedlist/linked_list.rs
  codes/rust/src/include/vertex.rs
Labels: code, polish

#1607 translation: refine translation of zh-hant hash_algorithm.md
  zh-hant/docs/chapter_hashing/hash_algorithm.md
Labels: translation, documents

#1591 translation: ram and cache
  en/docs/chapter_array_and_linkedlist/ram_and_cache.md
Labels: translation, documents

#1625 Fix python code style issue in linked list deque
  codes/python/chapter_stack_and_queue/linkedlist_deque.py
Labels: bug, code

#1626 Update heap_sort.md
  docs/chapter_sorting/heap_sort.md
Labels: bug, documents

#1621 add notation of m and n in analysis of complexity
  docs/chapter_dynamic_programming/dp_solution_pipeline.md
Labels: documents, polish

#1559 translation: update searching_algorithm_revisited.md
  en/docs/chapter_searching/searching_algorithm_revisited.md
Labels: translation, documents

#1618 Update binary_tree.md
  docs/chapter_tree/binary_tree.md
Labels: bug, code

#1557 translation: Update chapter_computational_complexity/performance_evaluation.md
  en/docs/chapter_computational_complexity/performance_evaluation.md
Labels: translation, documents

#1627 Bug fixes and improvements
  docs/chapter_computational_complexity/performance_evaluation.md
  docs/chapter_hashing/hash_algorithm.md
  docs/index.html
  en/codes/python/chapter_stack_and_queue/linkedlist_deque.py
  en/docs/index.html
  mkdocs.yml
  overrides/stylesheets/extra.css
  zh-hant/codes/python/chapter_stack_and_queue/linkedlist_deque.py
  zh-hant/codes/rust/chapter_array_and_linkedlist/array.rs
  zh-hant/codes/rust/chapter_array_and_linkedlist/linked_list.rs
  zh-hant/codes/rust/src/include/vertex.rs
  zh-hant/docs/chapter_computational_complexity/performance_evaluation.md
  zh-hant/docs/chapter_dynamic_programming/dp_solution_pipeline.md
  zh-hant/docs/chapter_hashing/hash_algorithm.md
  zh-hant/docs/chapter_sorting/heap_sort.md
  zh-hant/docs/chapter_tree/binary_tree.md
  zh-hant/docs/index.html
Labels: documents, polish

#1611 replace replace with take according to clippy suggestion
  codes/rust/chapter_hashing/hash_map_chaining.rs
Labels: code, polish
