Repository krahets/hello-algo, pull requests merged in 2025-03, with the labels that each got.

#1677 Improve the efficiency of function call
  codes/python/chapter_sorting/counting_sort.py
Labels: bug, code

#1688 Update the description of time and space complexity of fractional_knapsack problem.
  docs/chapter_greedy/fractional_knapsack_problem.md
Labels: documents, polish

#1711 fix(zh-hant translation): graph_traversal.md
  zh-hant/docs/chapter_graph/graph_traversal.md
Labels: bug, translation, documents
