Repository krahets/hello-algo, pull requests merged in 2025-07, with the labels that each got.

#1777 Polish rust
  codes/rust/chapter_array_and_linkedlist/my_list.rs
  codes/rust/chapter_heap/heap.rs
  codes/rust/chapter_stack_and_queue/array_deque.rs
  codes/rust/chapter_stack_and_queue/array_queue.rs
  codes/rust/chapter_stack_and_queue/linkedlist_deque.rs
  codes/rust/chapter_stack_and_queue/linkedlist_queue.rs
  codes/rust/chapter_stack_and_queue/linkedlist_stack.rs
  codes/rust/src/include/tree_node.rs
Labels: bug, code, polish

#1738 translation: Update en translation for preface
  en/docs/chapter_hello_algo/index.md
Labels: translation, documents

#1739 translation: Update EN translation for Introduction Chapter
  en/docs/chapter_introduction/algorithms_are_everywhere.md
  en/docs/chapter_introduction/summary.md
  en/docs/chapter_introduction/what_is_dsa.md
Labels: translation, documents

#1733 translation: Update algorithms_are_everywhere.md
  en/docs/chapter_introduction/algorithms_are_everywhere.md
Labels: translation, documents

#1770 Update performance_evaluation.md
  docs/chapter_computational_complexity/performance_evaluation.md
Labels: documents, polish

#1784 greedy/max_capacity: fix myMax algorithm error
  codes/c/chapter_greedy/max_capacity.c
Labels: bug, code
