Repository krahets/hello-algo, pull requests merged in 2025-02, with the labels that each got.

#1631 Translation: Update heap_sort.md
  en/docs/chapter_sorting/heap_sort.md
Labels: translation, documents

#1644 translation: chapter_sorting/index.md
  en/docs/chapter_sorting/index.md
Labels: translation, documents

#1554 translation: Update binary_search_insertion.md and binary_search_edge.md
  en/docs/chapter_searching/binary_search_edge.md
  en/docs/chapter_searching/binary_search_insertion.md
Labels: translation, documents

#1656 fix: update the implementation of simple_hash.js and .ts
  codes/javascript/chapter_hashing/simple_hash.js
  codes/typescript/chapter_hashing/simple_hash.ts
Labels: bug, code

#1672 Fix the comma in quick_sort.md
  en/docs/chapter_sorting/quick_sort.md
Labels: bug, documents
